### ISSUE TITLE
Supresion magica (Caballero de la muerte profano)

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#1]
El talento Supresión Mágica de la rama profano del dk no funciona. Segun la descripcion de la wotlk el tercer rango del talento deberia reducir un 6% el daño de hechizos recibidos y aumentar un 25% la capacidad de absorcion del caparazon antimagia pero aun teniendo los tres rangos puesto ese 25% no se aplica por lo que aunque te pongas el caparazon sigues recibiendo daños de hechizos aun teniendo el talento.

Caparazón Antimagia: http://es.wowhead.com/spell=48707
Supresión Mágica: http://es.wowhead.com/spell=49611/supresion-magica o http://www.wowhead.com/forums&topic=53183/magic-suppression

**Comment by Myst** [comment]
Reparado.
