### ISSUE TITLE
Golpe con runa 

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#10]
Spell :  Golpe con Runa
Error: Su daño es demasiado bajo, ademas en presecia sangre no se activa a menos que se bloquee, esquive o se pare un golpe, cosa que no es asi, en presencia de sangre debe estar siempre activado. 
Teniendo en cuenta que el daño del 180% es de arma (entre mas daño haga el arma mas daño hace al final de resultado,, esto significa que si la arma hace de 2142-3214 de daño usando la spell, un DK deberia de hacer (5997-7006 de daño para ser mas explicado, deberia de hacer un daño de 5997  p. de daño hasta 7006 p. de daño,  MÁS 2463 p. que en total al usarlo deberia de hacer un daño promedio de (9463 p. de daño ES OBVIO que ese no es el daño, TENIENDO en cuenta el poder de ataque de un jugador mas la fuerza que tenga y con el encantamiento de "Runa glaciar de ceniza" el golpe normal de la spell deberia ser de [ 10507 - a - 12786 ] de daño.(tomando en cuenta que el golpe seria siendo full implacable, si el arma cambia por una cata o una pve, este daño final aumenta)

Bueno espero que lo arreglen pronto, y si no, hagan las ecuaciones :D y veran que ese seria el daño que deberia hacer la spell.
Descripción de la spell:
Golpe con Runa
30 poder runico.     Alcance cuerpo a cuerpo
Instantáneo
Requiere arma cuerpo a cuerpo
Golpea al obejetivo y le inflije un 180% de daño con arma más 2462 p. Solo se puede usar en presencia de sangre, o 10s después de que el caballero de la muerte esquive o pare un ataque. Este ataque no se puede esquivar, bloquear ni parar y genera una gran cantidad de amenaza.

Hola quisiera reportar esta spell, ya que su daño no es el normal (Esta muy bajo), Deberia de hacer más DAÑO, no puedo poner el link, por que, ya no esta en Wowhead. mas sin embargo pondre las descripción.

**Comment by Myst** [comment]
El daño es correcto, debes considerar que para calcular el daño deberás usar la formula que se muestra en el siguiente link https://wow.freakz.ro/spells.php?spell=56815&name=rune-strike
