### ISSUE TITLE
Reporte del Glifo Pilar de Escarcha (DK)

### ISSUE THREAD

**Issue by MjDaftpunk** [Myst/Bugtracker#100]
Cuando pones el glifo de Pilar de escarcha este potencia tu pilar de escarcha haciendo inmune a los efectos de control del personaje, pero también inmoviliza a tu personaje en el mismo sitio mientras el hechizo está activo http://cata.openwow.com/item=43553

ERROR: 

El personaje ( DK ) no es afectado por su glifo, dando así una ventaja considerable al DK

![wowscrnshot_051015_052041](https://cloud.githubusercontent.com/assets/12310034/7553896/95f70d40-f6d4-11e4-8bf3-9c559da81204.jpg)
![wowscrnshot_051015_052050](https://cloud.githubusercontent.com/assets/12310034/7553897/9601981e-f6d4-11e4-86f2-c82416fd0bb7.jpg)
![wowscrnshot_051015_052056](https://cloud.githubusercontent.com/assets/12310034/7553898/9604c71e-f6d4-11e4-9112-28449fa0a502.jpg)
![wowscrnshot_051015_052058](https://cloud.githubusercontent.com/assets/12310034/7553899/96090a7c-f6d4-11e4-9556-381f6466a659.jpg)
![wowscrnshot_051015_052100](https://cloud.githubusercontent.com/assets/12310034/7553900/960c7248-f6d4-11e4-929b-7c075ea6af3c.jpg)

Como pueden ver en las imágenes el Glifo Pilar de escarcha no deja inmóvil al Dk en un solo lugar como dice el Glifo

**Comment by MjDaftpunk** [comment]
algo que me olvido es que también hace inmune  los efectos del sangrado cuando no debería ser así como pueden apreciar en las siguientes imágenes  de arriba y en estas :
![wowscrnshot_051015_052928](https://cloud.githubusercontent.com/assets/12310034/7553934/4e7841d0-f6d6-11e4-864f-21460a70316e.jpg)
![wowscrnshot_051015_052932](https://cloud.githubusercontent.com/assets/12310034/7553935/4e8ab838-f6d6-11e4-96db-61f490d8a3a3.jpg)

**Comment by Myst** [comment]
Reparado.

**Comment by MjDaftpunk** [comment]
Myst abrelo aún está activo el bug, al igual que otro bug del paladín

**Comment by Myst** [comment]
Aun no ha sido implementado.
