### ISSUE TITLE
Reporte del Hechizo Fulminación  ( Chamán ) 

### ISSUE THREAD

**Issue by MjDaftpunk** [Myst/Bugtracker#103]
Fulminación  es un hechizo de naturaleza con daño puro que hace el chamán http://es.wowhead.com/spell=88767/fulminacion  este hechizo dice que : 
Consume las cargas sobrantes de Escudo de relámpagos e inflige daño de Naturaleza a un objetivo enemigo de forma proporcional al número de cargas consumidas.

Error:

El chamán inflige un daño extra - normal  al que debe hacer con este ataque, compraré cuanto daño inflique con 3, 4, 5, 6, 7, 8, y 9 cargas para ver que tan alto es el daño que puede llegar a tener este hechizo.

3 cargas : daño normal varía entre ( 4700 a 5000 )
![wowscrnshot_051215_063216](https://cloud.githubusercontent.com/assets/12310034/7586256/b83acb74-f870-11e4-903c-a1f979956bb7.jpg)

4 cargas : daño normal varía entre ( 17 a 22k )  solo con 1 carga adicional
![wowscrnshot_051215_063319](https://cloud.githubusercontent.com/assets/12310034/7586270/e0120590-f870-11e4-9626-7151aefd3f6d.jpg)
![wowscrnshot_051215_063344](https://cloud.githubusercontent.com/assets/12310034/7586269/e00d3592-f870-11e4-8338-443d33c28020.jpg)

5 cargas : daño normal varía entre ( 25k a 44k )
![wowscrnshot_051215_063527](https://cloud.githubusercontent.com/assets/12310034/7586318/6a285afe-f871-11e4-9995-be90742d7ef1.jpg)
![wowscrnshot_051215_063710](https://cloud.githubusercontent.com/assets/12310034/7586319/6a2919da-f871-11e4-94c1-170707e2aec1.jpg)

6 cargas : daño normal varía entre ( 31k a 50k ) 
Aquí fulminación  infligió un daño critico de 43k 
![wowscrnshot_051215_064230](https://cloud.githubusercontent.com/assets/12310034/7586412/4927d090-f872-11e4-9cb1-b0f0303de656.jpg)
![wowscrnshot_051215_064258](https://cloud.githubusercontent.com/assets/12310034/7586411/4924e254-f872-11e4-8305-463613fab610.jpg)

7 cargas: daño normal varía entre ( 30k a 59k )
Aquí fulminación infligió un daño crítico de  53628 ( puden contrastarlo con el registro de combate)
![wowscrnshot_051215_064524](https://cloud.githubusercontent.com/assets/12310034/7586449/b125beb4-f872-11e4-819d-4669aacb595c.jpg)

8 cargas: daño normal varía entre ( 35k a 72k )
Aquí fulminación infligió un daño critico de 64025 ( puden contrastarlo con el registro de combate)
![wowscrnshot_051215_064751](https://cloud.githubusercontent.com/assets/12310034/7586578/eecbca96-f873-11e4-9e4c-5435367cba06.jpg)
![wowscrnshot_051215_065122](https://cloud.githubusercontent.com/assets/12310034/7586579/eece2cf0-f873-11e4-8515-e63537db97ae.jpg)
![wowscrnshot_051215_065428](https://cloud.githubusercontent.com/assets/12310034/7586580/eed4e7f2-f873-11e4-8e05-1499931b2063.jpg)

9 Cargas: daño normal varía entre ( 48k a 91k )
![wowscrnshot_051215_065707](https://cloud.githubusercontent.com/assets/12310034/7586656/bc469ec4-f874-11e4-9389-237957d78d81.jpg)
![wowscrnshot_051215_070012](https://cloud.githubusercontent.com/assets/12310034/7586657/bc4cc7cc-f874-11e4-94b6-92332869db58.jpg)
![wowscrnshot_051115_222427](https://cloud.githubusercontent.com/assets/12310034/7586704/28200c16-f875-11e4-8988-904b965847e5.jpg) 

Pueden contrastar el daño con el registro de combate que ahí especifica que daño causo, creo que es un daño exagerado porque Fulminación debería de pegar maximo un daño de 25k  como lo dice el Dr.damage con las 9 cargas.

**Comment by MjDaftpunk** [comment]
en las 4 cargas me equivoque y puse 22k cuando era 25k  ( testeaba recién levantando modo zombie ) xd  

PORFAVOR MIREN EL REGISTRO DE COMBATE.

**Comment by Myst** [comment]
Reparado.
