### ISSUE TITLE
Reporte Fin de los días

### ISSUE THREAD

**Issue by saphrina** [Myst/Bugtracker#104]
Buenas, realizamos la mazmorra Fin de los días completa. Todo funcionando ok, pero al matar a Murozond no recibimos ni logro ni lot. Buscábamos el logro para ingresar a otra mazmorra. Dejo unas imágenes aunque cuando hable con el Mj Letum ya había desaparecido el boss. Gracias!
http://es.wowhead.com/achievement=6117/heroico-fin-de-los-dias

![wowscrnshot_051215_222803](https://cloud.githubusercontent.com/assets/12420930/7602199/cc5ef094-f8f7-11e4-9a4f-21a8becba847.jpg)

![wowscrnshot_051215_222741](https://cloud.githubusercontent.com/assets/12420930/7602209/f1e306ca-f8f7-11e4-90d2-d5289b782fd1.jpg)

![wowscrnshot_051215_224132](https://cloud.githubusercontent.com/assets/12420930/7602217/15ecbfb6-f8f8-11e4-9246-3d40724eb395.jpg)

Imagen del boss muerto aportado por Naj
![123456](https://cloud.githubusercontent.com/assets/12420930/7602372/4d13f412-f8fa-11e4-8e71-227feac95bcf.jpg)

**Comment by Salinger2010** [comment]
Reparado. :)
