### ISSUE TITLE
Reporte Npcs bugs Tol barad Faccion Alianza (Misiones diarias y compras inaccesibles).

### ISSUE THREAD

**Issue by DrKillzone** [Myst/Bugtracker#105]
Reporte de los npc bugs con sus respectivos nombres y ids, tambien anexo fotos del testeo al acceso del npc. 

Id de Npcs Alianzas:
npc=47328 Quartermaster Brazie 
npc=48254 Sergeant Gray
npc=48066 sergeant parker
npc=48251 kevin geissler
npc=51288 major marsden
npc=48250 lieutenant farnsworth
npc=48074 marshal fallows
npc=48255 camp coordinator brack
npc=48039 commander stevens
npc=47240 commander marcus johnson
npc=48061 2nd lieutenant wansworth

![wowscrnshot_051315_113551](https://cloud.githubusercontent.com/assets/6827598/7615797/a9275828-f965-11e4-8ccd-fe71fe532945.jpg)
![wowscrnshot_051315_113557](https://cloud.githubusercontent.com/assets/6827598/7615798/a9300c34-f965-11e4-81e4-9f1ef927d454.jpg)
![wowscrnshot_051315_113602](https://cloud.githubusercontent.com/assets/6827598/7615800/a9358984-f965-11e4-97a8-ec21461c443a.jpg)
![wowscrnshot_051315_113606](https://cloud.githubusercontent.com/assets/6827598/7615802/a939b8d8-f965-11e4-9a1e-b63f64f05ee1.jpg)
![wowscrnshot_051315_113611](https://cloud.githubusercontent.com/assets/6827598/7615799/a9305568-f965-11e4-86f9-ccc7fd85a98f.jpg)
![wowscrnshot_051315_113533](https://cloud.githubusercontent.com/assets/6827598/7615801/a93621e6-f965-11e4-874f-8b601e0eaf90.jpg)
![wowscrnshot_051315_113538](https://cloud.githubusercontent.com/assets/6827598/7615803/a93d402a-f965-11e4-8897-80f2c380a89e.jpg)

**Comment by Myst** [comment]
Depende tu reputación....

**Comment by Sioned** [comment]
Hola esto pasa al entrar a una BG y salir de la facción contraria, solo debes reloguear y se arregla.
