### ISSUE TITLE
Set PvE Paladín

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#11]
http://es.wowhead.com/spell=105765/item-paladin-t13-retribution-2p-bonus-judgment
Sentencia otorga una carga de poder sagrado, eso esta bien, la cosa es que las demás spells tambien otorgan una carga de poder sagrado (Golpe de Cruzado otorga dos y Cólera sagrada 1-2-3 dependiendo de los objetivos).

http://es.wowhead.com/spell=105820/item-paladin-t13-retribution-4p-bonus-zealotry
Celo del Cruzado se mantiene activo a cada golpe, no solo durante "Fanatismo" como  deberia.

**Comment by Myst** [comment]
Los links son incorrectos y el reporte esta mal hecho. Esas auras solo consituyen un daño adicional para golpe cruzado y veredicto templario.
