### ISSUE TITLE
Infusion de luz bug 

### ISSUE THREAD

**Issue by Pullsee** [Myst/Bugtracker#110]
http://es.wowhead.com/spell=53576/infusion-de-luz Infusion de luz esta bug ya que al lanzar destello de luz no se va asi que los palas heals tienen destello de luz todo el rato instantaneo

**Comment by Myst** [comment]
Reparado.

**Comment by Pullsee** [comment]
no esta reparado

2015-07-27 7:00 GMT+02:00 Myst notifications@github.com:
