### ISSUE TITLE
Reporte de Reducción de Estadísticas ( Chamán ) 

### ISSUE THREAD

**Issue by MjDaftpunk** [Myst/Bugtracker#114]
Normalmente cuando tu invocas los totems del chaman, ya sea en mejora o elemental te aumentan o te dan una bonificación de acuerdo con los totems  invocados.

ERROR:

Como pueden ver estás son las estadísticas del chaman mejora 
![wowscrnshot_051515_035808](https://cloud.githubusercontent.com/assets/12310034/7650675/7171948e-fabe-11e4-8cd1-eaa759b71144.jpg)

Ahora  al poner totems todos sabemos que aumenta el daño dependiendo de que totems pones, aquí Kaseshini pone el Totem de Agilidad, y Viento furioso el cual aumentan estadísticas
![wowscrnshot_051515_035819](https://cloud.githubusercontent.com/assets/12310034/7650689/9b434ac8-fabe-11e4-8e39-754420269fd8.jpg)

Ahora que es lo que pasa cuando el activa su regreso totémico:
![wowscrnshot_051515_035827](https://cloud.githubusercontent.com/assets/12310034/7650711/d5735788-fabe-11e4-828f-a5b4a1c2b83c.jpg)

Como pueden ver a comparación de la Imagen #1  a la imagen #3  las estadísticas de poder de ataque, daño y celeridad,  en pocas palabras la agilidad más que todo es la estadística que se afecta y por ende disminuye, esto causa una desventaja a los chamanes mejora al pelear cuerpo a cuerpo. Cabe recalcar que muchos chamanes mejora se han quejado por esto y no solo es en mejora, también sucede en elemental y heal.

**Comment by Myst** [comment]
Reparado.
