### ISSUE TITLE
Problema barra de accion del elemental del mago frost de la cuenta rasf20

### ISSUE THREAD

**Issue by rasfesta** [Myst/Bugtracker#115]
Ante todo saludos.

Por error quite de la barra de accion del elemental del mago frost una de sus funciones espesificamente la de seguir al mago. Al abrir el libro de hechizos y tratar de colocar la funcion nuevamente en la barra. Este la coloca pero al ocualtar el elemental e invocarlo nuevemente la barra se reseta totalmente y la funcion que le habia colocado me la vuelve a quitar de la barra. Ya hice la prueba con todas las funciones del elemental, cambie de talentos y todo y sigue dandome ese problema.

**Comment by Myst** [comment]
Bloquea la barra del elemental para que no desaparesca.
