### ISSUE TITLE
Maestría chamán elemental

### ISSUE THREAD

**Issue by Ciannn** [Myst/Bugtracker#119]
Bueno, simplemente no funciona... Con el bono del set pve y ademas con el vortice transfigurador de almas llego a 87% de maestría. Esto significa 87% de probabilidad de que salga un segundo ataque. Eso que nisiquiera estoy reforjado a maestria o con gemas de maestria, con eso facilmente llegaria al 100% pero NO FUNCIONA!. 

Porfavor revisen esto, deje de jugar casi 1 año completo y en ese momento ya estaba este problema...  Como puede ser que siga sin funcionar?? 

dejo ss: http://i61.tinypic.com/fkyuyw.png

**Comment by Myst** [comment]
Hola, ten en consideración de que TODAS las clases tienen un límite de maestría, por lo que sobre ese tope no aumentará mas tu maestria, esto es así en el oficial, caso contrario porfavor presenta pruebas de que en retail no sea asi y se modificará.

**Comment by Ciannn** [comment]
pero entonces cual sería el límite en %?? debe ser extremadamente bajo ya que es muy difícil que salte el segundo ataque... y si es así, entonces no le veo el sentido a que exista tanto bono, abalorio, gemas y reforjas que te ayuden a llegar al máximo de maestría. ¿Tu me podrías presentar pruebas que en el oficial es así?, no lo digo por soberbia ni en tono desafiante, pero en verdad no lo sabia, y sinceramente no me hace ningún sentido.

**Comment by Myst** [comment]
Puedes revisar en todas las guías de wow, que siempre mencionan que no excedas cierto % de maestría porque no subirá el indice más. Por ejemplo, hay maestrias que mejorar el % de bloqueo, entonces si llegarán a 100% deberían poder bloquear todo y evidentemente no sería como tu dices lógico.

**Comment by Ciannn** [comment]
podrías darme el numero maximo de maestria del chaman porfavor?? para saber como armarme sin perder estadísticas.

**Comment by Myst** [comment]
Por lo que veo en las guias recomiendan que no excedas el 49%

**Comment by Ciannn** [comment]
Hmmm, y en el server la maestría esta ajustada a ese número? te pregunto porque aún con 50% cuesta mucho que salga el segundo ataque... 50% no es un porcentaje pequeño como para que de 10 ataques solo uno salga doble... me gustaría que algún dia logearas conmigo para revisar este tema, quiero que veas con tus ojos lo poco que salta la maestria.
