### ISSUE TITLE
reduccion de estadisticas al cambiar un items y volverse a poner el items anterior

### ISSUE THREAD

**Issue by Enfermera** [Myst/Bugtracker#127]
La reducción de mi estadistica no solo ocurre con los totems como le pasa a cualquier otro shaman sino tambien al cambiar un items ya sea yelmo, abalorio, anillo o todo el set y volver a poner el items anterior, ocurre si lo hace con el gertor de equipamiento como pasa en el video siguiente sino q tambien pasa cuando me cambio de items uno por uno y me vuelvo a poner el items q cambie, no se si esto pase solo con los shamanes pero si pasa con otra clase pon un comentario con la clase q tambien pasa este error 

https://www.youtube.com/watch?v=fzDNfE4duIA

**Comment by Myst** [comment]
Reparado.
