### ISSUE TITLE
Reporte del Set PvE ( Paladín )

### ISSUE THREAD

**Issue by MjDaftpunk** [Myst/Bugtracker#128]
Bueno el set pve del paladín tiene 2 bonificaciones de las cuales los paladines aprovechan:
![image](https://cloud.githubusercontent.com/assets/12310034/7676104/0cd3d8bc-fd06-11e4-9c6d-37d207145070.png)
Como pueden ver ese es el bono que da el set por cada sentencia aumenta 1 de poder sagrado.

Error :

El bono del set está correcto pero tiene un aumento considerable de poder sagrado, es decir que cualquier golpe del cruzado puede acumular de 3 a 6  de poder sagrado .
![wowscrnshot_051815_012646](https://cloud.githubusercontent.com/assets/12310034/7676491/d8c67b70-fd09-11e4-834a-212d1921b942.jpg)
![wowscrnshot_051815_012655](https://cloud.githubusercontent.com/assets/12310034/7676493/d8cb7e54-fd09-11e4-97ff-763541aa1133.jpg)
![wowscrnshot_051815_012713](https://cloud.githubusercontent.com/assets/12310034/7676492/d8cb7d00-fd09-11e4-96fa-be05ba2890dc.jpg)
![wowscrnshot_051815_022553](https://cloud.githubusercontent.com/assets/12310034/7676494/d8d8da0e-fd09-11e4-8908-8fdcaa698deb.jpg)

Esto permite al paladín generar mas poder sagrado y ganar mucho más poder con sus sanaciones y ataques que consumen poder sagrado dandole una considerable ventaja.

**Comment by kevin55555** [comment]
fuera lo mejor q areglaran eso porque q chiste pelar con un pala q se cura 40k acada rato  :(

**Comment by Myst** [comment]
Máximo se acumulan hasta 3 poderés sagrados...., así que aun cuando acumules más el cd de la curación te impide curarte repetidamente.

**Comment by MjDaftpunk** [comment]
pero siempre te da de 6 a 5 aveces 3 de poder sagrado y se que no siempre se cura porque tiene CD pero el hechizo http://es.wowhead.com/spell=85256/veredicto-del-templario  que es un poder para dañar, saca hasta 40k de critico con los 3 poderes sagrados, y si el paladín acumula mucho poder sagrado... imagínate cuantas veces podría meter ese poder D:

**Comment by Myst** [comment]
No es eso, te sale que tienes 3 poder sagrado no que te estan dando 3 de poder sagrado....... El límite es 3 no se acumula más que eso.
