### ISSUE TITLE
diaipar magia

### ISSUE THREAD

**Issue by makavelo00** [Myst/Bugtracker#131]
Gm revisa el poder disipar magia no se deja usar y cuando metes el glifo de disipar magia tiene que curar 3 % de salud cuando disipo un efecto y no sirve porfavor revisalo grax por la atencion

**Comment by makavelo00** [comment]
Ese poder es del sacerdote sahdown gm

**Comment by MjDaftpunk** [comment]
Normativa de reporte de errores de juego

1.- Los errores de juego deberán estar bien reportando, cualquier falta de información en los reportes conllevara al cierre del reporte. Siempre que sea posible se requerirán enlaces concretos a sitios web como wowhead o wowfreakz donde la información se pueda contrastar.

2.- Los errores de juego repetidos se cerrarán automaticamente. Busquen de reportar algo que pueda estar ya reportado.

3.- Solo un error de juego por reporte.

4.- Deben colocar la etiqueta para el tipo de error de juego que esten reportando.

5.- No se admiten fallos personales con los PJ como "mi pj se ha atascado" o "no puedo completar esta quest". Si se admitirán del tipo "Spell no funciona", "quest no funciona", etc.

6.- Un mal uso del bugtracker podrá conllevar a la expulsión del usuario del mismo (con la cuenta de github creada previamente para publicar).

7.- Cualquier otro tipo de reporte deberá hacerse via foro (aún no implementado) o vía skype: a myst.infernalwow, los errores como atascamiento u otros menores deberán ser reportados vía ticket.

Falta de pruebas para que sea arreglado, te recomiendo mirar otros Post y repotar lo más similar ese hechizo que indicas, gracias.

**Comment by Myst** [comment]
Duplicado
