### ISSUE TITLE
Reporte del Poder Ejecutar ( warrior )

### ISSUE THREAD

**Issue by MjDaftpunk** [Myst/Bugtracker#135]
Bueno, en el guerrero hay 2 clases de ejecutar en armas http://es.wowhead.com/spell=163201/ejecutar, y en furia y proteccion http://es.wowhead.com/spell=5308/ejecutar

como bien nos especifica el poder 
![image](https://cloud.githubusercontent.com/assets/12310034/7699775/fe4cd21e-fddf-11e4-86bc-91b43f33555b.png)
Puede llegar hasta un 405% de daño extra consumiento 30p de ira.

ERROR:

El poder de remate Ejecutar del guerrero no inflige el daño que debería de hacer, ya que Ejecutar es como el remate del guerrero o golpe final.
![wowscrnshot_051915_042759](https://cloud.githubusercontent.com/assets/12310034/7699931/e4dc5b00-fde0-11e4-991a-4556aee8061d.jpg)
![wowscrnshot_051815_184202](https://cloud.githubusercontent.com/assets/12310034/7699945/f73da114-fde0-11e4-8380-1b334ee1dc73.jpg)
![wowscrnshot_051815_184120](https://cloud.githubusercontent.com/assets/12310034/7699954/02469408-fde1-11e4-81b6-510331610019.jpg)
![wowscrnshot_051815_184204](https://cloud.githubusercontent.com/assets/12310034/7699962/1561b518-fde1-11e4-97a1-161e4849912f.jpg)

Como pueden ver el daño apesar que tenia  90 puntos de ira me consumió todos los puntos de ira solo para causar 12k de critico, el daño está demasiado bajo para ser un remate final del guerrero y deberia de consumir de 10 puntos de irá a 30 para causar más daño .. no 90 puntos de irá :-1: , por eso los jugadores prefieren no usar este talento. 

POSTDATA: Revisar el registro de combate para que comprueben cuanto daño hizo ejecutar.

**Comment by MjDaftpunk** [comment]
![wowscrnshot_051815_183812](https://cloud.githubusercontent.com/assets/12310034/7700052/9b69db86-fde1-11e4-858c-72c8fa65d400.jpg)
![wowscrnshot_051815_183815](https://cloud.githubusercontent.com/assets/12310034/7700053/9b6f1312-fde1-11e4-9ae9-edb014a588ea.jpg)

Registro de combate ( daño de Ejecutar )

**Comment by Myst** [comment]
Revisa la media de daño, no la media de daño critico, el daño es correcto.
