### ISSUE TITLE
Bug de establo de pets [Cazador]

### ISSUE THREAD

**Issue by Lauraxse** [Myst/Bugtracker#142]
Este es un problema algo grave para nosotros los cazadores ya que no podemos guardar ni poner las pets mostrare el npc con el que se guarda o se guardaba las pets en ventormenta [Alianza]:
http://es.wowhead.com/npc=44252/karin

hablabamos con ella y retirabamos pets de nuestros silvatos y poniamos otras y asi pero ahora no anda porfavor arreglenlo lo antes posible

**Comment by Myst** [comment]
Reparado.
