### ISSUE TITLE
 [Disipar magia]

### ISSUE THREAD

**Issue by makavelo00** [Myst/Bugtracker#144]
gm  el poder  [Disipar magia] no sirve i cuando metes el glifo  [Glifo de Disipar magia] tendria que curarte el 3% de de tu salud maxima http://es.wowhead.com/item=42415/glifo-de-disipar-magia   areglalo gm no se deja usar ese poder grax :)

**Comment by Myst** [comment]
Porfavor sube un screenshot donde se muestre la descripción del glifo, debido a que en wowhead no se menciona en ninguna parte que el glifo deba aumentar 3% de tu salud máxima.

**Comment by linux01** [comment]
![image](https://cloud.githubusercontent.com/assets/12422745/7846389/8c9a98f8-0493-11e5-8e6b-8d82f39f1704.png)

**Comment by Myst** [comment]
Si no respondes en 2 días más será cerrado,

**Comment by makavelo00** [comment]
![wowscrnshot_053015_052547](https://cloud.githubusercontent.com/assets/7000400/7897939/92514fa2-06b5-11e5-9157-e3951a97f979.jpg)

**Comment by makavelo00** [comment]
gm cuando elimino un efecto maligno no cura nada ese es el problema

**Comment by makavelo00** [comment]
por eso no uso ese glifo

**Comment by Myst** [comment]
Reparado en la siguiente revisión.
Gracias por el reporte.
