### ISSUE TITLE
mision bug

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#15]
http://nsae02.casimages.net/img/2015/03/27/150327045125580887.jpg
La mision de inicio de la raza gnomos "See to the survivors" consiste en usar un objeto de mision para teletransportar objetivos pero estos no son teletransportados, el objeto se usa pero no se cuenta en la mision ni tampoco se mueve el objetivo..

**Comment by Myst** [comment]
Reparado.
