### ISSUE TITLE
Talento: Amenaza de Thassarian

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#152]
Reporte de bugs.
Clase: Caballero de la muerte.

---

Talento: Escarcha.
Habilidad: Amenaza de Thassarian.

Talento único en dk escarcha, define el modo de uso del caballero de la muerte -con armas a una mano-. Dicho talento permite al dk que use armas de una mano, inflingir daño con arma izquierda, dándole dps en cada empuñadura.

![talento dk amenaza de tishiran](https://cloud.githubusercontent.com/assets/12435844/8021296/693959d4-0c5f-11e5-92a0-563777ff4f48.png)

El talento consiste en sólo permitir que el arma de mano izquierda inflinja daño, DAÑO... Lo que sucede ahora con este talento es que emula los ataques y efectos de la empuñadura de mano derecha, y esto se ve reflejado en [Golpe letal].

![habilidad golpe letal](https://cloud.githubusercontent.com/assets/12435844/8021300/8659dde0-0c5f-11e5-8d8a-41d3ddf64be1.png)

Golpe letal es una de las principales habilidades de supervivencia del dk, con el efecto que de la [Amenaza de Thassarian], el dk logra curarse el doble de lo que debe curar generalmente, ya que el arma de mano izquierda imita los efectos de los ataques que se hagan con la derecha, dicho de otra forma, el arma de mano izquierda debe lanzar sólo daño, mas no dar con efectos como el de [Golpe letal].

![bug amenaza de tasharoan](https://cloud.githubusercontent.com/assets/12435844/8021308/bc9a34cc-0c5f-11e5-9d26-0934639fc6f2.png)

Con ello, el dk puede alcanzar una sanación exagerada con tan solo lanzar [Golpe letal], como se ve en la imagen. Siendo así, puede alcanzar 100K de sanación lanzando 5 letales seguidos (si le alcanzan las runas).

**Comment by Cimeries** [comment]
Y que pasaria si se junta el proc de la runa cruzado caído con el golpe letal en un mismo golpe???
No se solo consulto.

Slds.

**Comment by Myst** [comment]
Ya se explico esto.
