### ISSUE TITLE
Talento: Infusión de luz

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#153]
Reporte de bugs.
Clase: Paladín.

---

Talento: Sagrado.

Infusión de la luz, talento que aumenta el efecto crítico de choque sagrado, además de reducir el tiempo de varias facultades de sanacuín cuando se activa su efecto.

![talento paladin infusion de luz](https://cloud.githubusercontent.com/assets/12435844/8025349/d54eccd0-0d18-11e5-8b24-b7e453927122.png)

Una vez activo el efecto de infusión de la luz, el paladín puede lanzar en menos tiempo varios hechizos, como Luz sagrada, Luz divina o Destello de luz, pero el efecto dura hasta que el paladín castee el hechizo. Es decir, apenas se activa, el paladín sólo tiene un lanzamiento del hechizo que desee lanzar, una vez lanzado, el efecto se cancela.

Actualmente este talento permite lanzar, mientras dure su efecto, infinitas veces destello de luz. 

![habilidad paladin destello de luz](https://cloud.githubusercontent.com/assets/12435844/8025353/f52f1d84-0d18-11e5-9ee2-a4df5fa84053.png)

Es decir, que una vez que el efecto de infusión de la luz empieza, el paladín puede lanzarse sin castear estas sanaciones, logrando helearse mucho más de lo debido, ya que los destellos de luz serían, mientras esté el talento activo, prácticamente infinitos.

![bug infusion de luz](https://cloud.githubusercontent.com/assets/12435844/8025356/0fdd93b8-0d19-11e5-8f12-30e467d69ee5.png)

(Aclaro, mi personaje está sañoso por eso cura tan poquito) En la imagen se puede observar que se han lanzado dos destellos de luz seguidos mientras que el efecto de infusión de la luz sigue activo, cuando en realidad ese efecto debería acabarse cuando se lanza apenas el primer destello. (Imaginen lo que hace un full cata :V )

**Comment by Myst** [comment]
Reparado.
