### ISSUE TITLE
Barra de Energia Druida Equilibrio.

### ISSUE THREAD

**Issue by b3l1al** [Myst/Bugtracker#156]
Nose como explicar esto pero tratare de ser lo mas sencillo posible, Como saben el druida equilibrio mas llamado "pollo" tiene una barra de energia que va de 0 y dependiendo que casteo uses siendo estos dos "colera" y "fuego estelar" son los que hacen que la barra vaya de un lado a otro...

El error aca es cuando estas casteando "colera" para llegar a "eclipse lunar" , hasta ahi todo bien... pero el problema esta que cuando uno por error castea "fuego estelar" se pierde energia en ves de quedar tal cual esta ..... un ejemplo claro seria este " llevas 90 casi llegando a eclipse lunar y casteas "fuego estelar" pierdes 20 puntos de energia en ves de mantenerse la barra de energia en los 90 anteriores.

Nose si se entendio, si quieres añado fotos.

**Comment by Myst** [comment]
Claro que entiendo tu reporte, sin embargo, así es como debe funcionar la barra, de modo que si casteas fuego estelar suficientes veces volerá a 0.
