### ISSUE TITLE
Mision de inicio huargen

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#16]
http://es.wowhead.com/quest=14212/sacrificios
No deja montar el caballo,no se mueve, no hace nada debería ser funcional la misión para que el huargen pueda conseguir sus raciales  
http://es.wowhead.com/quest=28850/el-tejado-de-la-prision
y estos npc no se encuentran y no creo que funcionen

**Comment by Myst** [comment]
Reparado.
