### ISSUE TITLE
instructor de clase DK Lady alistra

### ISSUE THREAD

**Issue by Mjletum** [Myst/Bugtracker#160]
EL instructor de clase Dk no enseñan la doble especializacion,
 Lady Alistra 
http://es.wowhead.com/npc=28471/lady-alistra
![wowscrnshot_061515_201146](https://cloud.githubusercontent.com/assets/12877245/8167155/a542aaf4-139c-11e5-9497-2d57a417e061.jpg)

**Comment by Myst** [comment]
Reparado.
