### ISSUE TITLE
Instructor de clase Dk Lord Thorval

### ISSUE THREAD

**Issue by Mjletum** [Myst/Bugtracker#161]
El instructor de clase Dk Lord Thorval no enseña doble especialización de talentos
http://es.wowhead.com/npc=28472/lord-thorval

![wowscrnshot_061515_201102](https://cloud.githubusercontent.com/assets/12877245/8167243/35626782-139d-11e5-94d9-1d832b8e14fb.jpg)

**Comment by Myst** [comment]
Reparado.
