### ISSUE TITLE
Instructor de clase DK Amal'thazad

### ISSUE THREAD

**Issue by Mjletum** [Myst/Bugtracker#162]
El instructor de clase DK Amal'thazad no enseña doble especialización de talentos
http://es.wowhead.com/npc=28474/amalthazad
![wowscrnshot_061515_201014](https://cloud.githubusercontent.com/assets/12877245/8167290/81b25912-139d-11e5-99f3-8c725151e917.jpg)

**Comment by Myst** [comment]
Reparado.
