### ISSUE TITLE
bugg de entrada del bancal del magister 

### ISSUE THREAD

**Issue by mayvidal94** [Myst/Bugtracker#165]
como pueden ver en la imagen no se puede ingresar a la mazmorra del bancal del magister en modo heroico porque pide ser mayor que 65 y pues somos 85 .... el premio de perseverancia de esta estancia es la montura que pueden ver en la segunda imagen.
![wowscrnshot_061615_225703](https://cloud.githubusercontent.com/assets/12929977/8199459/0bf24ef6-147b-11e5-8870-02dcd4c5c9ad.jpg)

**Comment by Cimeries** [comment]
OMG,este Desolado esta por todos lados.XD

**Comment by Salinger2010** [comment]
Para poder entrar en modo heróico, debes primero completar la cadena de misiones en modo normal.
