### ISSUE TITLE
Habilidad: Golpe necrótico.

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#167]
Reporte de bugs.
Clase: Caballero de la muerte.

---

Talento: Escarcha - Profano - Sangre.
Habilidad: Golpe necrótico.

Algunas clases cuentan con herramientas que les permiten reducir la sanación en el oponente, véase [Golpe mortal] en el guerrero armas, [Veneno hiriente] en el pícaro o incluso el talento [Escarcha permanente] en el mago escarcha. Estos reducen la cantidad sanada por el objetivo.
La habilidad del caballero de la muerte que permite controlar los efectos de sanación en el objetivo es [Golpe necrótico]. Este golpe actúa de manera diferente a las reducciones de sanación comunes, ya que no reduce determinado porcentaje de sanación, sino que absorbe una cantidad determinada en función del poder de ataque, además de aumentar el tiempo de casteo.

![habilidad dk golpe nectotico](https://cloud.githubusercontent.com/assets/12435844/8213593/911a145c-14e8-11e5-9706-72ca40c38fb0.png)

Golpe necrótico es una habilidad acumulable, es decir, que con cada golpe que se dé al objetivo la sanación que se absorve se debe acumular. Si en este momento absorve 10358 p, con un segundo golpe necrótico absorvería: 20716 p. Y si se pegan 5 necróticos, absorvería 51790 p.

En este momento, Golpe necrótico no se acumula, por lo que la sanación absorvida es constante y no acumulable, dejando perdida una función vital en la habilidad.

![big necrotico 1](https://cloud.githubusercontent.com/assets/12435844/8213644/02ac4928-14e9-11e5-9280-f4d94b0e42e2.png)

Como se ve en las imágenes, la cantidad absorvida en los dos momentos lanzados [Golpe nectótico], es la misma, cuando lanzando los necróticos (mientras el efecto siga activo) se debería acumular.

**Comment by Myst** [comment]
Si revisas la descripción del hechizo, hay un límite en la cantidad de sanación que se acumula la cual es 10358.
