### ISSUE TITLE
BUG Cuenca de Arathi

### ISSUE THREAD

**Issue by YukihiraInfernalwow** [Myst/Bugtracker#172]
Bueno ya que aqui esta implementada las BG mixta permitame explicarle el siguiente bug en este campo de batalla.

EL bug es el siguiente: Si soy horda ( ejemplo) y entro como alianza a bg en algunas ocasiones se bugea la base, de la siguiente forma: si la base es de la horda, y yo soy horda pero entre como alianza a bg, la bg me reconoce como un horda por tanto no puedo robar base, Osea si soy horda y entro a bg como ali en algunas ocasiones no puedo robar la base porque el juego reconoce que soy horda, lo mismo pasa si soy alianza y entro a bg como alianza....

**Comment by Myst** [comment]
Reparado.
