### ISSUE TITLE
sacer sombra 

### ISSUE THREAD

**Issue by makavelo00** [Myst/Bugtracker#18]
gm primero quiero hablarte de http://es.wowhead.com/spell=34433/maligno-de-las-sombras   no sirve no regenera mana  

Masoquismo http://es.wowhead.com/spell=88995#see-also-ability no te sube mana cuando te golpean un 10% de tu salud en lo absoluto

gracias por su atencion prestada tt yuyix =)

**Comment by Myst** [comment]
Maligno de sombrás solo regenerá mana al morir si tienes el glifo.
Masoquismo reparado.
Gracias por el reporte.

**Comment by makavelo00** [comment]
Gm lo que te esplicaba del maligno de las sombras es que no ataca estando es estado agresivo el debe atacar directo no ataca se queda hay parado sin haser nada grax por tu atencion

**Comment by makavelo00** [comment]
Al no atacar el maligni el sacer no regenera mana
