### ISSUE TITLE
Ulduar

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#181]
Esta banda esta compuesta de torres hacia el camino del primer jefe el cual esta rodeado de enanos http://www.wowhead.com/npc=33572/steelforged-defender pues por ello los usuarios deben derrivar las torres para que estos no vuelvan a parecer

ERROR: los enanos son inmortales la cual hacen imposible ir hacia el primer jefe.

Cuando la banda traspasa el primer boss se encuentran con 3 mas, los cuales no tienen ningun Error Pero cuando se quiere ir hacia la siguiente recamara http://es.wowhead.com/achievement=2888/la-antecamara-de-ulduar-10-j el teleport no se encuentra disponible y eso hace que los usuarios no puedan completar la banda al 100%
![wowscrnshot_062315_140739](https://cloud.githubusercontent.com/assets/13021789/8314759/2d2e91c0-19b1-11e5-869b-256dfaf25644.jpg)

**Comment by Zodiako** [comment]
Para ayudar el post añado la foto de los enanos inmortales:
![wowscrnshot_062315_035952](https://cloud.githubusercontent.com/assets/12379432/8391612/b5911238-1c8e-11e5-8302-93e9ba7251f5.jpg)
Además el primer boss es intargeteable:
![wowscrnshot_062315_040136](https://cloud.githubusercontent.com/assets/12379432/8391620/f110ad14-1c8e-11e5-907a-b50b2e20d209.jpg)

**Comment by Myst** [comment]
ya fue reparado.
