### ISSUE TITLE
Maestría elemental [Chaman]

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#185]
Este poder http://es.wowhead.com/spell=16166/maestria-elemental tal como dice tiene que durar 3 minutos pero solo dura 10 segundos o menos y eso le da ventaja al chaman ya que tiene revolcafango ilimitado y mas celeridad

**Comment by Salinger2010** [comment]
El tiempo de reutilización es de tres minutos.
Con el talento [Retroacción] se le permite reducir ese tiempo de reutilización unos pocos segundos lanzando descargas de relámpagos. Eso, si el chamán tiene muchas oportunidades de castear, puede suponer reducir el tiempo de reutilización de [Maestría elemental] de a un minuto o más, siempre que el chamán logre castear.
