### ISSUE TITLE
Runas de la muerte (caballero de la muerte)

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#199]
Cuando un dk obtiene las runas de la muerte hace que sus runas duren un poco mas y eso hace que el dk tenga mas ataques de golpe de la peste http://es.wowhead.com/spell=57599/golpe-de-peste , golpe letal http://es.wowhead.com/spell=49998/golpe-letal , asolar http://es.wowhead.com/spell=49020/asolar etc.

ERROR: cuando un dk ingresa a una bg o arena se les bugea las runas de la muerte, por lo tanto es una gran desventaja y tambien cuando le hacen uso desaparecen al istante

**Comment by Myst** [comment]
verificar si el problema continua y reabrir en caso sea así.

**Comment by Salinger2010** [comment]
![dk runas 1](https://cloud.githubusercontent.com/assets/12435844/8911031/a20a5db8-344f-11e5-8f00-85d5dfb2a1fd.png)
![dk runas 2](https://cloud.githubusercontent.com/assets/12435844/8911070/d4a24fe2-344f-11e5-8b9a-9d3c93ad16f5.png)

En las imágenes se puede ver que el caballero de la muerte, recién, está con sus runas como deben ser. Al cambiar de ambiente (cruzando un portal, o yendo a una bg, o incluso aceptando una invocación) sus runas vuelven a ser "de sangre".

![habilidad dk sangre del norte](https://cloud.githubusercontent.com/assets/12435844/8911172/7418aa4e-3450-11e5-87a5-d500e145e7a5.png)

Link: https://wow.freakz.ro/spells.php?spell=54637

Este hechizo/talento pasivo del dk, le otorga una conversión permanente de las runas "de sangre" como runas "de la muerte". Las runas de la muerte cuentan como runas de sangre, escarcha o profanas, con lo que el dk puede usar hechizos y generar sus ataques.
