### ISSUE TITLE
Poderes de paladines

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#203]
El poder de  [Inquisición] http://es.wowhead.com/spell=111341/inquisicion del paladin que aumenta un 30% de daño al acumular 3 sagrados pero cuando se le renueva a este con 3 sagrados nueva mente se bugea el conteo lo cual lo deja en 11 segundos siempre y debe renovarlo desde el inicio que es 36 segundos.

Cuando un paladin se aplica  [Escudo divino] http://es.wowhead.com/spell=642/escudo-divino cuando esta activo el paladin tiene menos dps ya que cuando lo activan dice claramente que el dps disminuye un 50% pero hay un error que el cual el paladin que se aplique el escudo no puede acumular los sagrados.
![11660417_823029527766707_516119576_o](https://cloud.githubusercontent.com/assets/13021789/8344809/b123d5f8-1aab-11e5-8f0a-6498ce929839.jpg)

**Comment by Zodiako** [comment]
Lo de no poder generar poder sagrado mientras se está inmune jode bastante =(

**Comment by Myst** [comment]
no es ningún error, no debe acumular poder sagrado mientras esta inmune.
