### ISSUE TITLE
Abalorio  [Fetiche de vínculo de huesos]

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#207]
El abalorio  [Fetiche de vínculo de huesos] http://es.wowhead.com/item=77210/fetiche-de-vinculo-de-huesos al activarse de hacer cierto daño a area por 10m lo cual es muy util contra oponentes a casteo y hunters su cd es aproximado 20 segundos calculablemente.

ERROR: La version normal y buscador de bandas de este abalorio no cumple con el cd lo cual lo hace ventajoso para los mele ya que se activa seguidamente.

**Comment by Zodiako** [comment]
No sé como funcionará en la versión buscador de bandas, pero en la versión normal el abalorio no hace daño, solo tiene el bug visual de girar, si hacen el testeo con algún addon de control de dps o miran el registro de combate, verán que no hace daño.

**Comment by Myst** [comment]
Reparado
