### ISSUE TITLE
talento o spell del dk bug 

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#21]
http://es.wowhead.com/spell=54637/sangre-del-norte Este hechizo o talento por asi decirlo hace que siempre las runas de sangre se conviertan en muerte a cada rato y es una desventaja para los dk
2° El segundo bug o error de este spell hace que cuando el dk entra a los campos de batalla las runas de muerte se conviertan en sangre

**Comment by Myst** [comment]
No es un bug, se supone que eso debe hacer.
