### ISSUE TITLE
Bug clase cazador (orbe de sombras)

### ISSUE THREAD

**Issue by Mjletum** [Myst/Bugtracker#221]
la clase cazador tienen un hechizo que no es de cazador, es de sacerdote sombras.
http://es.wowhead.com/spell=95740/orbes-de-las-sombras
![bug caza orbe sombras](https://cloud.githubusercontent.com/assets/12877245/8397458/20b55752-1dcc-11e5-86b0-ad854deee0ff.jpg)

**Comment by Myst** [comment]
Reparado,
