### ISSUE TITLE
Abalorio [Nido del último dragón] N y BdB

### ISSUE THREAD

**Issue by Mj-Nigthsoul** [Myst/Bugtracker#233]
Este objeto carece de tiempo de reutilización.

http://es.wowhead.com/item=77205/nido-del-ultimo-dragon 
![wowscrnshot_063015_122052](https://cloud.githubusercontent.com/assets/13122066/8436624/6781cf6e-1f23-11e5-847f-bbd46c789f0d.jpg)

http://es.wowhead.com/item=77972/nido-del-ultimo-dragon
![wowscrnshot_063015_122129](https://cloud.githubusercontent.com/assets/13122066/8436645/86dafe1c-1f23-11e5-919a-68dce9a0aa38.jpg)

Su tiempo de reutilizacion esta entre los 110seg.

**Comment by Myst** [comment]
Eso se llama ICD no es un bug.
