### ISSUE TITLE
Bug de Caparazón antimagia [Caballero de la muerte]

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#242]
Cuando un dk se aplica Caparazón antimagia http://es.wowhead.com/spell=48707/caparazon-antimagia le da inmunidad a cualquier hechizo dañino y evita aplicaciones magicas dañinas como el [Ciclón] http://es.wowhead.com/spell=48707/caparazon-antimagia Del druida, lo cual lo hace muy util contra paladines, magos, brujos, chamanes, y druidas.

ERROR:Cuando el echizo del dk esta activo hay ciertos hechizos que pueden afectarle al dk lo cual no debe ser asi cuando esta activo el escudo lo cual es algo desventajoso para los dk que se aplican este poder.

**Comment by Myst** [comment]
Realmente carapazon antimagia no repele todo los hechizos.
