### ISSUE TITLE
Habilidad: Bola de fuego

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#258]
Reporte de bugs.
Clase: Mago.

---

Talento: Fuego.
Hechizo: Bola de fuego.

Habilidad básica del mago fuego, y la primera con la que nace el mago en nivel 1. Se lanza una bola de fuego a gran distancia que inflinge daño de fuego moderado.

![habilidad mago bola de fuego](https://cloud.githubusercontent.com/assets/12435844/8509104/7197dddc-2256-11e5-80b9-87d1b17ac25d.png)

El problema está en que su daño está aumentado excesivamente. Logrando sacar críticos de 30K o más, a personajes con 5K de temple.  (Censuro nombres para evitar disputas)

![dano bola de fuego](https://cloud.githubusercontent.com/assets/12435844/8509111/178137f2-2257-11e5-8314-c4198c1cd2e9.png)

El daño a personajes con temple de la bola de fuego es: 

![dano real bola de fuego](https://cloud.githubusercontent.com/assets/12435844/8509125/ad29b4a0-2257-11e5-92dd-8cafcf86bfa3.png)

El daño de esta habilidad es exagerado. Supera el daño estándar en un 128% (aproximadamente). (Y más si llevan equipo PvE, que también está bug… después hablaré de ello)

**Comment by Myst** [comment]
Hola, lamentablemente tu reporte carece de pruebas (fuentes) que prueben que el daño debería estar cercano a las cantidades que tu señalas. Por otro lado tengo entendido que el daño de bola de fuego se encuentra correcto. Desde luego estamos dispuestos a revisar el tema siempre que presentes pruebas sobre este tema. Agradeceré que si encuentras alguna prueba seas tan amable de abrir un nuevo reporte.
