### ISSUE TITLE
Abalorio  [Orgullo indómito]

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#261]
El abalorio  [Orgullo indómito] http://es.wowhead.com/item=78003/orgullo-indomito tiene de funcion de que cuando el usuario de este baja al 50% de vida otorga un escudo de absorcion igual a un 50% de vida del usuario durante 6 segundos y su cd es de 60 segundos.

ERROR:Cuando el usuario de este abalorio llega al 50% de vida este no se activa, lo cual no cumple lo que dice y tambien hace inutil al tanke que aporte este abalorio lo cual no deberia ser haci el error de este abalorio esta tanto en normal, heroico , buscador de banda

**Comment by Myst** [comment]
Reparado.
