### ISSUE TITLE
Segunda especialización de talentos, instructores Caballeros de la Muerte

### ISSUE THREAD

**Issue by Naaj** [Myst/Bugtracker#273]
Los siguientes NPCs son los únicos Instructores de los Caballeros de la Muerte, ninguno te da la opción de aprender la segunda especialización de talentos. Solo te deja aprender hechizos y borrar talentos.

http://www.wowhead.com/npc=31084/highlord-darion-mograine
http://www.wowhead.com/npc=29194/amalthazad
http://www.wowhead.com/npc=29196/lord-thorval
http://www.wowhead.com/npc=29195/lady-alistra

![image](https://cloud.githubusercontent.com/assets/12243028/8513724/686df3f6-2344-11e5-86d6-c0e055dcf430.png)

**Comment by Myst** [comment]
Reparado.
