### ISSUE TITLE
Stun del mago 

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#278]
Cuando infligen daño tienen una posibilidad de obtener un stun instant llamado  [Impacto] el cual aturde al jugador durante 3 segundos.

ERROR:Este poder se activa varias veces lo cual no debe ser haci ya que tiene un 10% de activarse.

(Este poder ya no existe en wow head, lo cual no puedo linkearlo)

**Comment by Zodiako** [comment]
Eh? eso está bien, la probabilidad no tiene cooldown, así sea 10% con suerte se puede activar varias veces seguidas, además la duración del stun se reduce si se aplica correctamente, o sea todo anda bien.

**Comment by MjYoruishi** [comment]
osea, pegas un stun y instantaneamente te aparece otra que es eso xd? ni se acerca a tener un 30% y se activa seguidamente.

**Comment by Zodiako** [comment]
Pongo la imagen del talento:
![impacto](https://cloud.githubusercontent.com/assets/12379432/8754417/08ca3cd6-2c89-11e5-83ed-fdc0a0d02adc.jpg)
Dice claramente, que todos los hechizos dañinos tienen un 10% de reiniciar el tiempo de explosión de fuego, y explosión de fuego también es un hechizo de daño, así que es lógico que pueda activarse con el mismo hechizo, y si tienes mucha suerte podría activarse cuantas veces más se quiera, y por cierto, las máximas veces seguidas que se me ha activado el talento fueron como 4 veces, y solo pasó una vez, solo es cuestión de suerte, por que de ser posible, lo es.

**Comment by MjYoruishi** [comment]
pero es un 10% no cambia tanto, ni el talento del pala que hay un 30% de posibilidad de mantener los sagrados aunque los usen, cambio este spell se activa cada 6 seg xd

**Comment by Myst** [comment]
Reparado en la siguiente revisión.
