### ISSUE TITLE
 Talento [Amenaza de Thassarian]

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#294]
Cuando el dk usa 2 espadas es favorable puntear el talento  [Amenaza de Thassarian] http://es.wowhead.com/spell=66192/amenaza-de-thassarian ya que gracias a este tienen un 30% de infligir daño dependiendo del poder golpe letal http://es.wowhead.com/spell=49998/golpe-letal , asolar http://es.wowhead.com/spell=49020/asolar , golpe de peste http://es.wowhead.com/spell=57599/golpe-de-peste  y golpe de escarcha http://es.wowhead.com/spell=49143/golpe-de-escarcha

ERROR:Cuando usan golpe letal este los cura 2 veces lo cual es un bug ya que no dice que cure sino que inflige daño.

**Comment by Myst** [comment]
duplicado.
