### ISSUE TITLE
¿Buffs invisibles?

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#296]
Reporte de bugs
## Clase: Mago.

A continuación mostraré imágenes de un bug visual que no permite los buffs, tanto beneficiosos como malos que recaen sobre el mago, puedan verse como tal.

Aún no tengo entendido cómo se genera, y ocurre sólo a los magos, muchos han presentado este problema.

Mostraré imágenes para que se entienda el problema:
- Cuando se sube a una montura, esta no aparece seleccionada, ni tampoco aparece en el espacio de buffs (al lado de luminosidad arcana y armadura de arrabio), pero aún así aparece como si se estuviera montando. (Además, esto hace que no pueda desmontar cuando se está en vuelo)

![lagarta montura](https://cloud.githubusercontent.com/assets/12435844/8557877/d2c0bbc6-24c5-11e5-9c8b-df2ffcf1fca1.png)
-  Los escudos y efectos beneficiosos del mago como [Escudo de maná], [Armadura de mago], y [Velocidad llameante] tampoco aparecen registrados.

![lagarta escudos](https://cloud.githubusercontent.com/assets/12435844/8557919/32c1d69a-24c6-11e5-83c9-0aac211b4a91.png)
- Escribo aparte el de [Bloque de hielo] ya que hace algo muy particular. Al activarse, no registra como tal el bloque, da inmunidad sin tener el bloque además de no dar su efecto de [Hipotermia]...

![lagarta bloque](https://cloud.githubusercontent.com/assets/12435844/8558043/3551abaa-24c7-11e5-89cf-c569d77be383.png)
- Los efectos negativos de otros jugadores sean la clase que sean no se pueden ver, aunque están generando daño constante. Véase [Desgarrar] del guerrero, [Sello de verdad] del paladín, [Picadura de serpiente] o [Veneno de viuda] del cazador, sangrados del druida, enfermedades del dk, pestes del sacer, incluso las quemaduras del mago...

![lagarta desgarrar](https://cloud.githubusercontent.com/assets/12435844/8558237/6c9adedc-24c8-11e5-995b-81bcc14ead83.png)

![lagarta sello](https://cloud.githubusercontent.com/assets/12435844/8558262/9e465006-24c8-11e5-8b66-69bf6765c65c.png)

![lagarta picadura](https://cloud.githubusercontent.com/assets/12435844/8558286/cbc45cb2-24c8-11e5-9459-3c8d79be35aa.png)

Y así con muchos buffos más... 
Es raro, dado que sólo le sucede a los magos.

Agradecimientos: Reptilia, por dejarme ver el bug de cerca  <tres

**Comment by Myst** [comment]
Reparado.
