### ISSUE TITLE
Glifo: Polimorfia

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#298]
Reporte de bugs
## Clase: Mago

![glifo mago poliforma](https://cloud.githubusercontent.com/assets/12435844/8579561/edd7aa22-257a-11e5-903a-4b77e249b137.png)

El glifo consiste en quitar todos los efectos de daño periódicos cuando el objetivo recibe el efecto de Polimorfia.

El problema está en que no quita nada, haciendo el glifo totalmente inútil.

![bug poliforma](https://cloud.githubusercontent.com/assets/12435844/8579748/08209726-257c-11e5-8321-164378a5fa5f.png)

El glifo debería purgar la bomba viva y dejar sólo el efecto de polimorfia activo sobre el objetivo.

**Comment by Myst** [comment]
Todos los efectos de DAÑO periódicos, esto quiere decir que se trata de los efectos negativos que causan dao periódico sobre el objetivo.

**Comment by Salinger2010** [comment]
Bomba viva es daño periódico. Al aplicar polimorfia sobre el objetivo éste debe purgarse. (Teniendo el glifo, claro)
