### ISSUE TITLE
Abalorios bug:[Sello de los siete símbolos] Heroic y normal

### ISSUE THREAD

**Issue by Kotaix** [Myst/Bugtracker#305]
Spam en buenas condiciones aunque tiene un BUG, el abalorio se está activando por mele, por causar daño y dice que debe ser por SANACION. Así que revisar que ocurre con el tanto el Heroic como el normal.

![1](https://cloud.githubusercontent.com/assets/13264565/8610298/bc6ea398-2686-11e5-9ab9-aaabb140a9c7.JPG)

Activándose como ven sin que el "testpicaro" este usando “reponer” o algo que lo esté curando, solo mele y se activa
![2](https://cloud.githubusercontent.com/assets/13264565/8610307/e10a5ed6-2686-11e5-82b2-3aecf56b0cc4.JPG)

GM KOTAIX

**Comment by Myst** [comment]
Reparado.
