### ISSUE TITLE
Abalorios bug:[fetiche de vinculo de huesos] Normal y Heroic

### ISSUE THREAD

**Issue by Kotaix** [Myst/Bugtracker#306]
fetiche de vinculo de huesos NORMAL:

Su spameo es mayor sobretodo en condiciones de alta celeridad mele pero aun así al menos recount  detecto daño de mele ni de alguna habilidad como el caso del vial de sombras. Por lo demás si puede decir que la animación de cuando se activa el abalorio ocurre con mayor frecuencia en este abalorio normal que en el heroic, al igual que en casi todos los abalorios pve testeados.

fetiche de vinculo de huesos Heroic  
Spam de máximo 30 seg entre activación y activación.

GM KOTAIX

**Comment by Zodiako** [comment]
Está bug el normal al menos, no hace daño de ningún tipo, el efecto es meramente visual.

**Comment by Myst** [comment]
Reparado.
