### ISSUE TITLE
Abalorios bug: [Insignia de mente corrupta] Normal y heroic

### ISSUE THREAD

**Issue by Kotaix** [Myst/Bugtracker#307]
[Insignia de mente corrupta] :Heroic  

Funcionamiento y spameo funcionales y correctos

[Insignia de mente corrupta] Normal 

Al igual que los demás abalorios normales ya estudiados presenta un spameo continuo de un 90% de spameo, al igual que todos los demás calculado como tiempo activado vs tiempo total y estudiado 3 veces el test para obtener un promedio del promedio, más la cantidad de veces de activación en dicho tiempo. Su activación ocurre en promedio de cada 2seg a máximo 5 seg (casi igual que los demás abalorios normales ya estudiados).

Observando los tiempos de hacer picadillo se puede observar con facilidad:
![3](https://cloud.githubusercontent.com/assets/13264565/8610403/1dab506a-2688-11e5-97ea-f315d29f165f.JPG)

GM KOTAIX

**Comment by Myst** [comment]
Reparado.
