### ISSUE TITLE
Abalorios bug: [Vortica transfigurador de almas] HEROIC Y NORMAL

### ISSUE THREAD

**Issue by Kotaix** [Myst/Bugtracker#308]
Siendo el único abalorio que esta bug tanto el heroic como el normal. Este abalorio tiene un % de activación de 95% es decir que su spameo de maestría es constante cada un promedio máximo de 4 a 5 seg, no hay más que decir sobre este abalorio que realmente desestabiliza el equilibrio de clases ya que ciertas clases como el dk y el druid con esta abalorio pueden bugear su daño.

![4](https://cloud.githubusercontent.com/assets/13264565/8610457/a50581c0-2688-11e5-80ce-379b245a662c.JPG)

Su % de activación logro tocar 0 (osea desactivarce) solo por 2 seg, por lo demás su spameo en promedio según lo calculado es de un 85% aprox, siendo esto muy bug ya que si un abalorio se activa entre 3 a 19 seg entre spam y spam significara que el abalorio siempre estará dando el buff y con esto rompiendo las clases y desequilibrando el pvp.

![5](https://cloud.githubusercontent.com/assets/13264565/8610465/b8e168b2-2688-11e5-9b5e-71688690fb3a.JPG)

En resumen el buff de los abalorios tanto del heroic como el del normal estarán activos todo un duelo de mele o cada vez que el pj tenga contacto físico con el enemigo. Totalmente bug el spam de este abalorio tanto del normal y del heroic como ya mencione.

GM KOTAIX

**Comment by Myst** [comment]
Reparado. Es vortice no vortica.
