### ISSUE TITLE
Abalorios bug:[Nido del ultimo dragón] normal y heroic

### ISSUE THREAD

**Issue by Kotaix** [Myst/Bugtracker#309]
[Nido del ultimo dragón] Heroic  
Al igual que la mayoría de los abalorios  HEROIC tiene un correcto funcionamiento, siendo su spameo de activación bajo, activándose en un promedio de cada 2 a 3min.

[Nido del ultimo dragón] normal 

Al igual que los demás abalorios normales testeados esta con un spameo bug, siendo este contanstante  y nunca acabandoce mientras se golpee al enemigo. Al igual que “brújula cazaestrelas” en solo 1 min el abaslorio se activó 5 veces siendo su % de activación de un 99% mientras se este golpeando al enemigo. 

![4](https://cloud.githubusercontent.com/assets/13264565/8610503/2ad6a73e-2689-11e5-9541-196952ffd85c.JPG)

A continuación se puede demostrar que el abalorio en tan solo 1 min se activó 5 veces

![5](https://cloud.githubusercontent.com/assets/13264565/8610510/3ddfcc84-2689-11e5-8fec-7de5aec240d0.JPG)

GM KOTAIX

**Comment by Myst** [comment]
Reparado.
