### ISSUE TITLE
Abalorios bug: [Brújula cazaestrellas] normal

### ISSUE THREAD

**Issue by Kotaix** [Myst/Bugtracker#310]
[Brújula cazaestrellas] normal
Su % de spam es de 95% , el abalorio se activa cada un promedio de 3 a 5 seg.
![1](https://cloud.githubusercontent.com/assets/13264565/8610533/8497df68-2689-11e5-9d6a-91d86c7022c8.JPG)

Este abalorio genera que tengas 2904p de celeridad siempre ya que nunca llegara a 0 el buff mientras espes golpeando ya que como se testeo nunca logro ser desactivado durante todo el duelo u toda la bg.  Spam bug total.
![2](https://cloud.githubusercontent.com/assets/13264565/8610536/8a9bdfc2-2689-11e5-90ee-285167a13189.JPG)

GM KOTAIX

**Comment by Myst** [comment]
Reparado.
