### ISSUE TITLE
Abalorios bug: [Brújula cazaestrellas] heroic

### ISSUE THREAD

**Issue by Kotaix** [Myst/Bugtracker#311]
Su % de spam es “normal” , ya que se activa en promedio una vez por duelo, en un duelo de 3 a 4 min de duración su activación fue de 1 vez
![3](https://cloud.githubusercontent.com/assets/13264565/8610551/cfed7c34-2689-11e5-9c01-7a2af200d76a.JPG)

AUMENTAR SU SPAM NO SERIA MALO

TESTEO EN BG

Tras el testeo se obtuvo que el abalorio se activa cada un promedio de 10 min o cambio de objetivo .
![4](https://cloud.githubusercontent.com/assets/13264565/8610558/eaa937f2-2689-11e5-9523-2a19c506b195.JPG)

**Comment by Myst** [comment]
Reparado.
