### ISSUE TITLE
Abalorios bug: [Vial de las sombras] Heroic

### ISSUE THREAD

**Issue by Kotaix** [Myst/Bugtracker#312]
Considerando que a mayor golpes de mele tenemos mas probalidad de su activación es testeo se realizo utilizando el abalorio “brújula” para ganar celeridad extra además de “Hacer picadillo” (habilidad que también aumenta la celeridad)
![1](https://cloud.githubusercontent.com/assets/13264565/8610574/1fa4271e-268a-11e5-8e68-e87ba4babc6c.JPG)

Prueba Tras 2 min de prueba El abalorio Spameo 3.2%  igual a solo 3560 de daño…nada

![2](https://cloud.githubusercontent.com/assets/13264565/8610581/41c1dcc4-268a-11e5-8594-f603398281d2.JPG)
Esta prueba fue realizada 2 veces utilizando solo mele y 2 utilizando cds y en todos los casos el % de activación del abalorio es muy bajo y realmente inútil para un jugador.

Prueba de solo mele

Prueba que duro 4 min y en el cual se obtuvo lo sigiente
![5](https://cloud.githubusercontent.com/assets/13264565/8610587/6021eaec-268a-11e5-9d1a-1cbd40c07958.JPG)

Mas fotos que lo demuestran: 

![6](https://cloud.githubusercontent.com/assets/13264565/8610599/9421ba0c-268a-11e5-9b24-444f8f91339f.JPG)

Siendo su activación de un 4.4% y causando 5400 de daño, siendo este el daño TOTAL de las 2 veces que se activó, realmente no contribuye en nada al Dps

GM KOTAIX

**Comment by Myst** [comment]
Reparado.
