### ISSUE TITLE
Abalorios bug:[Vial de las sombras] normal

### ISSUE THREAD

**Issue by Kotaix** [Myst/Bugtracker#313]
Adiferencia del Heroic y como casi todos los abalorios normales tiene un spameo exesivo el cual es causante de romper el juego y desiquilibrarlo.

Para este testeo solo se utilizo “hacer picadillo” y aun asi el spameo fue execivo
![1](https://cloud.githubusercontent.com/assets/13264565/8610622/ed21951e-268a-11e5-9961-44877b0e64a0.JPG)

Siendo tras 1 min a casi puro mele activado un 36% llegando casi a superar al % de mele como 33k mele y 31k daño realizado por el abalorio.

En otra prueba de principalemte solo  mele obtuvimos tras 2min aprox el siguiente resultado

![2](https://cloud.githubusercontent.com/assets/13264565/8610627/fa0f1aee-268a-11e5-9779-e55aa4b9f429.JPG)

Siento es demasiado ya que aunque su % de activación fue de un 27% su daño fue el segundo más alto siendo más alto que todas las habilidades utilizadas, menos hemorragia, hasta el punto de superar el mele, por lo demás su daño fue de 105k como pueden ver en la imagen.

![3](https://cloud.githubusercontent.com/assets/13264565/8610631/18c6e9a8-268b-11e5-980e-800c51f7751a.JPG)

repito: bajar el spam pero no convertirlo en un item inservible 

GM KOTAIX

**Comment by Myst** [comment]
Reparado.
