### ISSUE TITLE
 [Poción de ilusión]

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#337]
http://es.wowhead.com/item=58489/pocion-de-ilusion
Esta poción tiene una funcion algo divertida la cual te transforma en tu objetivo, es una poción muy famosa ya que te hace transformar en diferentes cosas y todo eso.

ERROR:Cuando se usa esta poción esta no te transformas en tu objetivo, a estado erronea desde ase años..

**Comment by Myst** [comment]
Reparado en la siguiente revisión, gracias por el reporte.
