### ISSUE TITLE
Loot de  [Murozond]

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#367]
http://es.wowhead.com/npc=54432/murozond
Se supone que al derrotar  [Murozond] aparece un cofre con aspecto de dragon, pero cuando lo matan no aparece ningun cofre.
![wowscrnshot_072215_120708](https://cloud.githubusercontent.com/assets/13021789/8832272/a0c5abd2-306d-11e5-8018-9ff05367c9ef.jpg)

**Comment by Myst** [comment]
Reparado.
