### ISSUE TITLE
Jefe  [Eco de Tyrande] Fin de los dias

### ISSUE THREAD

**Issue by MjYoruishi** [Myst/Bugtracker#368]
http://es.wowhead.com/npc=54544/eco-de-tyrande
Este jefe es uno de los ultimos de esta mazmorra y al iniciar la pelea comienza a invocar ciertos gatos y guardias, pero tambien algunas luces las cuales sirven para debilitar a sus soldados ya que ellos obtienen un 90% de aguante en la oscuridad, pero cuando los jugadores quieren atacarla no pueden..
![wowscrnshot_072215_120538](https://cloud.githubusercontent.com/assets/13021789/8832383/4d93be62-306e-11e5-818e-63bb9d66bcb8.jpg)

**Comment by Salinger2010** [comment]
Primero se deben apagar todas las luces para poder atacar al boss. 
Las etapas comienzan con los tigres. Hay que ir a matarlos continuamente bajo cada luz, una vez las luces sean extinguidas, el boss quedará funcional.
