### ISSUE TITLE
Alizzabal (farmeo)

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#37]
http://es.wowhead.com/npc=55869/alizabalEste boss no debe rrespawnear en solo 10 o 15min en realidad debe ser reapwneado para dentro de 4 dias Muchos players farmean este boss y abusan de ello.

**Comment by Kr4v3n5** [comment]
los boss deben respawn 1 semana no 4d por seaca

**Comment by Myst** [comment]
Reparado.
