### ISSUE TITLE
Logro: Heróico fin de los días.

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#371]
Reporte de bugs. 
## Mazmorra: Fin de los días.

Mazmorra de la expansión "cataclysm" que cuenta con cinco bosses. 
El logro se obtiene al matar al último de estos cinco: Murozond.

El error está en que no da logro ni lot, haciendo en vano toda la mazmorra.

![fin de los dias bug](https://cloud.githubusercontent.com/assets/12435844/8891940/a50df770-3302-11e5-8346-6d2fce12b910.png)

En la imagen se ve que la mazmorra se completó totalmente (se necesita matar a cada boss para avanzar). Pero, aún estando el boss final muerto no otorga el debido logro.

Al completar la mazmorra y obtener el logro, se abre la entrada a otra mazmorra: Pozo de la eternidad

**Comment by Myst** [comment]
Reparado en el siguiente reinicio.
