### ISSUE TITLE
Bug Fin de los Dias - Murozond

### ISSUE THREAD

**Issue by RokkanJC** [Myst/Bugtracker#373]
Boss: http://es.wowhead.com/npc=54432/murozond#drops

Bug:
-No dice sus dialogos respectivos
-Avisos de sus ataques en ingles
-Al acabar con Murozond, no te otorga los respectivos logros (tambien pasa con los bosses anteriores a este en esta instancia)

Fuente:
http://i.imgur.com/hjQcz7h.jpg

**Comment by Myst** [comment]
Aún no se ha realizado el reinicio.

**Comment by Myst** [comment]
Murozond ya otorga sus respectivos logrós.
Los dialogos ya han sido añadidos y podrán ser revisados en el siguiente reinicio.
