### ISSUE TITLE
Firelands: Entrada bug

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#374]
Reporte de bugs.
## Raid: Tierras de fuego.

Estás armando una raid con tus amigos. Todos listos para entrar a la raid cuando: ¡Oh! ¡No se puede!

Bien, así es. La entrada de la raid está bug, dado que no se puede entrar de una manera normal. 
Explícitamente, cuando se va a ingresar a la raid por la entrada, el persinaje corre hacia ella como si estuviera chocando contra una pared y el acceso es casi imposible. (La única forma -que conozco- de entrar es desconectándose y al conectarse presionar "W" muchas veces, es la manera que conozco)

![firelands bug entrada](https://cloud.githubusercontent.com/assets/12435844/8922449/a13a8db4-34a8-11e5-9598-0037258c33e4.png)

En la imagen se ve que trato de entrar. Si se está en banda, se puede lograr la entrada a esta raid, pero pareciera que un muro me impide el paso en toda la entrada.

**Comment by Myst** [comment]
Se supone que solo se debe entrar mediante una quest.
