### ISSUE TITLE
Alma de Dragón: Viajes en los dragones

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#377]
Reporte de bugs.

Raid: Alma de dragon.

---

Una vez derrotado Morlock -primer jefe que encontramos en Alma de Dragón- encontraremos estos tres dragones que nos llevarán a las distintas localizaciones de los siguientes bosses.

![dragon soul - viajes](https://cloud.githubusercontent.com/assets/12435844/8946266/aa162bf8-3554-11e5-99c1-732e304d5d87.png)

Cada uno de estos dragones nos lleva a un jefe específico.
- Verde [Calavera] = Lleva a Señor de la guerra Zon´ozz
- Dorado [Cuadro] = Lleva a Yor´Sahj el Velador
- Rojo [Equis] = Lleva a la parte de arriba de la torre, donde encontraremos varios npc, donde posteriormente nos enfrentaremos a Hagara, la vinculavientos.

(Después contra Ultraxion y Alamuerte :D )

El bug de ahora está en que los el dragón dorado no sirve. Una vez es derrotado el Señor de la guerra Zon´oz (una batalla muy dura), el acceso a este dragón nos es dado y podremos ir a combatir el próximo boss. Pero, el dragón nunca llega y directamente nos manda al vacío.

![dragon soul - viaje1](https://cloud.githubusercontent.com/assets/12435844/8946505/75625376-3556-11e5-99ff-fa94ae63d64b.png)

En la imagen se ve cómo llevé a todo el grupo hacia el abismo. :(

El dragón debería dar con su destino, que es la plataforma para enfrentar al tercer boss de la raid Yor´Sahj el Velador, pero nunca llega.

Dejo un vídeo del funcionamiento adecuado de estos dragones. Además de la banda en sí.

Link: https://www.youtube.com/watch?v=7SCjzvmIwnI (Desde 1:51)

**Comment by Myst** [comment]
Reparado.
