### ISSUE TITLE
Cuenca de Arathi: Cambio de banderas

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#381]
Reporte de bugs.
## Campo de batalla: Cuenca de Arathi.

La implementación de un sistema de bg mixto en el cual se disponga a equilibrar los oponentes en los campos de batalla, es muy buena opción a la hora  de dar combates estables.

Sin embargo, en cuenca de Arathi no sucede tal cosa con exactitud. 
Éste campo de batalla consiste en cambiar cinco bases y resistir con las bases tomadas el mayor tiempo posible. El problema está en que cuando sales horda en la alianza o, por el contrario, alianza en la horda no es posible cambiar dichas bases, teniendo más probabilidades de perder la bg.

![cambio de bandera](https://cloud.githubusercontent.com/assets/12435844/9023293/201000aa-385b-11e5-8a5e-963c00c1d3ea.png)

En esta bg, siendo alianza, me tocó como horda. En la bg no puedo cambiar las banderas alianzas por als de mi equipo temporal (horda)...

**Comment by Myst** [comment]
Reparado.
