### ISSUE TITLE
Bug visual profesiones

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#382]
## Reporte de bugs.

![profesiones](https://cloud.githubusercontent.com/assets/12435844/9023785/923f3690-3870-11e5-98f8-44f25cb191b2.png)

La imagen habla sola. Al abrir la ventana donde se muestran las profesiones primarias y secundarias (en mi caso encantamiento y joyería), una de las dos profesiones presenta un bug visual. Joyería -caso mío- aparece de una manera muy extraña y es imposible seleccionar la profesión desde ahí, aunque en realidad sigo teniendo la profesión.

![profesiones2](https://cloud.githubusercontent.com/assets/12435844/9023790/e1e747f0-3870-11e5-9114-fbdcc43f473e.png)

En la imagen se ve que presento un bug visual cuando abro la pestaña de las profesiones, pero gracias a que coloqué [Joyería] en la barra de hechizos puedo abrir dicha profesión.( y sigue funcionando de manera adecuada.)

**Comment by Myst** [comment]
Solo debes reportarlo ingame para que un maestro de juego te ayude.
