### ISSUE TITLE
Objeto de mision bug-

### ISSUE THREAD

**Issue by Cimeries** [Myst/Bugtracker#383]
Buenas,les traigo un deleite para sus bugeadas.El objeto a tratar es http://es.wowhead.com/item=69240/balsamo-encantado  lo entrega el NPC http://es.wowhead.com/npc=53080/capitan-troncoferro en Frente de Magma,para realizar la mision  http://es.wowhead.com/quest=29138 (cabe destacar que esta bug esta mision,no que puede curar a los Defensores de Hyjal heridos).
En fin,cuando se obtiene este item te da la opcion de curarte o curar a cualquier NPC o PJ,la sanacion es de 50k aprox. y su cd es de 1seg y medio,tambien se puede utilizar en combate.
Les dejo un print de mi dk curandose infinitamente.

[url=http://subefotos.com/ver/?5190cfc59d71ad8bf97b8d4adf73e700o.png] [img]http://thumbs.subefotos.com/5190cfc59d71ad8bf97b8d4adf73e700o.jpg[/img][/url]

**Comment by Myst** [comment]
Gracias por el reporte.
