### ISSUE TITLE
Poción: Jarabe de guerra

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#384]
Reporte de bugs.
## Objeto: Jarabe de guerra.

Poción que permite curarte 25K de salud y 10K de maná, usado sólo en campos de batalla.

![objeto - jarabe de guerra](https://cloud.githubusercontent.com/assets/12435844/9240348/99e7d45c-412a-11e5-8a6f-9c853fc68f08.png)

El error en este objeto, es que permite su uso a la velocidad de clickeo del jugador, es decir, al tener un macro o la poción en la barra de poderes se puede usar tantas veces se dé click.

Acá algunas pruebas:

![jarabe de guerra 2](https://cloud.githubusercontent.com/assets/12435844/9240457/4b06a2b2-412c-11e5-9981-3020d0610358.png)
![jarabe de guerra](https://cloud.githubusercontent.com/assets/12435844/9240458/4b08c844-412c-11e5-8c9c-299297f6038c.png)

En las fotos se ve cómo puedo usar las pociones para curarme repetidas veces. (Fue en vano, me mataron cuando le tomé foto :c ). En fin, la poción puede renovar la vida totalmente si se usa de una forma bestial como esta. (Lo hice para reportar, no para buguear, no me odien. T.T)

**Comment by Myst** [comment]
Reparado.
