### ISSUE TITLE
Habilidad: Gubia

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#386]
Reporte de bugs.
## Clase: Pícaro.

Hechizo: Gubia.

Gubia, es un hechizo que incapacita a los objetivos afectados, cualquier daño inflingido durante su efecto, cancelará el mismo.

Éste, es un hechizo de incapacidad principalmente, no de daño y, aunque genere un poco de daño, no es el objetivo del mismo.

El problema con esta habilidad es que está generando mucho más daño -muuucho- del que le corresponde. A continuación mostraré a mi pícaro, con el equipo que tiene, estadísticas y junto a él el daño de Gubia.

![habilidad picaro - gubia](https://cloud.githubusercontent.com/assets/12435844/9290158/eafb11b8-434d-11e5-889e-27440e437d8c.png)

Dr. Damage es un addon usado para medir el daño objetivo de las clases -esta mide el daño conforme al nivel y estadísticas principales-. Este daño es a objetivos SIN temple, pero, sin embargo es una herramienta importante, dado que permite medir qué tanto está aumentado el daño en algunas facultades.

En la foto se puede ver el daño general de Gubia. Lo acercaré para que se pueda ver detalladamente:
![habilidad picaro gubia2](https://cloud.githubusercontent.com/assets/12435844/9290175/54d5b214-434e-11e5-9a4f-35f8a323288f.png)

En la foto se ve el daño generado. 
Un golpe normal debe sacar de a  (2798 - 2799)
Un golpe crítico debe sacar de a   (5763 - 5766)
Todo eso conforme al equipo que tiene el pícaro. (A objetivos full temple el daño se reduce aproximadamente un 50%)

El caso es que ahora, Gubia está desfasado de daño, he aquí:

![gubia bug 2](https://cloud.githubusercontent.com/assets/12435844/9290217/ca75ac30-434f-11e5-959e-3c3459ad8816.png)

Actualmente, un golpe normal de Gubia quita de a 18K (Puede quitar más dependiendo la rama que sea el pícaro)

![gubia bug 1](https://cloud.githubusercontent.com/assets/12435844/9290226/2a635ab6-4350-11e5-9db1-4509f031dae4.png)

Y en crítico, saca de a 38K... 

![wowscrnshot_042715_095523](https://cloud.githubusercontent.com/assets/12435844/9290302/b1a0e992-4352-11e5-8c96-52619d45f677.jpg)
![wowscrnshot_042715_095723](https://cloud.githubusercontent.com/assets/12435844/9290303/b1ab268c-4352-11e5-84e4-30ae6dea9031.jpg)
![wowscrnshot_042715_100051](https://cloud.githubusercontent.com/assets/12435844/9290304/b1afff36-4352-11e5-90a7-363a430297c1.jpg)

Y más pruebas...
El daño de esta habilidad está muy por encima de lo normal.

**Comment by acdcallan** [comment]
Toda la razón

**Comment by Myst** [comment]
Reparado. Gracias
