### ISSUE TITLE
Bola de fuego (Magos)

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#39]
http://es.wowhead.com/spell=9053/bola-de-fuego
http://es.wowhead.com/spell=61909/bola-de-fuego
http://www.wowhead.com/spell=133/fireball Este spell esta muy elevado es decir sus lanzamientos generan 5.6k de daño pero tal como dice wow head deberia sacar 3.5k llegando a 4.6k
y sus criticos deberian ser de 12.5k.

**Comment by Myst** [comment]
recuerda que wowhead esta en la versión 6.1.2

**Comment by Myst** [comment]
Reparado.
