### ISSUE TITLE
Aliviar espiritu

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#40]
http://es.wowhead.com/spell=90361/aliviar-espiritu Descripción: La bestia espíritu sana al objetivo amistoso actual [1371 + ((Ranged attack power \* 0.35) \* 0.5)] p. más [527 + ((Ranged attack power \* 0.35) \* 0.335)] p. extra durante 10 s.
Problema: No cura nada o su curación anda baja.

**Comment by Myst** [comment]
Reparado en el siguiente reinicio.
