### ISSUE TITLE
Bug Frasco de mejora

### ISSUE THREAD

**Issue by MjOmeteuhtli** [Myst/Bugtracker#401]
El objeto "Frasco de mejora" es exclusivo de alquimistas, aumentando 80 puntos de tu estadística más elevada, ya sea fuerza, agilidad o intelecto, es el único frasco que también se puede usar en arenas. El problema es que anda bug, y no da el efecto ni las estadísticas que dice al consumirlo.
Link wowhead: http://es.wowhead.com/item=58149/frasco-de-mejora
PD: en wowhead dice que ya no está disponible por el cambio de expansión, pero en cataclysm debería funcionar normalmente.

**Comment by Myst** [comment]
Reparado.
