### ISSUE TITLE
Explosión aullante

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#402]
Reporte de bugs.
Clase: Caballero de la muerte.
Talento: Escarcha.

---

Uno de los principales ataques en la rotación de un dk cuando está a nivel 85, este hechizo inflinge una oleada de escarcha la cual daña al enemigo 10.000 de daño aproximadamente.

Muchos de nosotros (digo nosotros porque me ha pasado) nos hemos quejado del daño que hace dicha habilidad (por ello algunos dk la spamean tanto)... En el siguiente post se verá el daño de esta habilidad y cómo está aumentado.

Usaré el addon "Dr. Damange" para analizar el daño de la explosión, dicha herramienta muestra el daño de cada una de las habilidades de acuerdo con el nivel, estadísticas y buffs que se tengan, a objetivos SIN temple. Acá dejaré un link para que lo descarguen por si desean comprobarlo.
http://www.wowace.com/addons/dr-damage/files/?page=142&sort=name

... Continuando con el tema...

![habilidad dk explosion aullante todo](https://cloud.githubusercontent.com/assets/12435844/9718788/8ad6120c-5544-11e5-9c41-9c981bf3a7a2.png)

La anterior imagen muestra el daño que debería hacer la explosión en mi caballero de la muerte. Un daño normal de 10219, y un daño crítico de 22883. (Mas el daño de fiebre de escarcha, 7 tics que suman 10K)

![explosion aullante 1](https://cloud.githubusercontent.com/assets/12435844/9718944/ac4ef3a8-5545-11e5-8cfa-6764fa6c051d.png)
Empezamos... La imagen habla por sí misma. Donde se debería sacar 10K , la explosión inflinge un daño de 14454, eso es aproximadamente un 40% más del daño que debe hacer originalmente.

![explosion aullante 2](https://cloud.githubusercontent.com/assets/12435844/9719235/1c390184-5548-11e5-8804-48591299eadd.png)
Y qué decir del daño crítico... de 22K pasa a 30208 de daño... eso es un 30% más, aproximadamente.

A decir verdad, frente a este daño no hay tanto problema, no hace mucha diferencia frente a los jugadores o los moobs, es poco... El problema es cuando los dk se ponen abalorios como el [Vórtice transfigurador de almas] [Luchador de fosa] o incluso [Nido del último dragón]

Usaré los abalorios que más usan los dk para spamear este ataque y son: [Vórtice transfigurador de almas] y [Nido del último dragón], ambos heróicos.

![explosion aullante maestria 1](https://cloud.githubusercontent.com/assets/12435844/9719367/3c4d1694-5549-11e5-9133-f23d9526fc34.png)
Ahí está el daño de la explosión con los dos abalorios activos... 14862 daño normal y 31061 daño crítico.

![explosion aullante maestria 2](https://cloud.githubusercontent.com/assets/12435844/9719411/9f3096fa-5549-11e5-80be-67450bdfe993.png)
El daño rebasa la cantidad límite. De quitar 14862, ahora la explosión daña 24965... Eso es un 67% más, el daño la explosión es potenciado, por ello es que algunos dk spamean tanto este ataque llevando puestos estos abalorios.

![explosion aullante maestria 3](https://cloud.githubusercontent.com/assets/12435844/9719493/4deee304-554a-11e5-96cd-54e3c7bb8ab3.png)
Y qué decir del daño crítico, que inflinge un 52% más de daño. Debería quitar 31061, y no los 52175 que quita ahora.

Sé que dirán "Pero hey... eso es daño a objetivos son temple. ¿Qué hay de los jugadores?"... Bueno, en los jugadores es peor.

Si las explosiones bajan en promedio un daño normal de 10400 usando todo el equipo PvP a un objetivo sin temple... el daño se reduciría de un 45 a 50% si golpea a un jugador con el mismo equipo, es decir, si golpeo a otro dk full temple, el daño que era de 10219, se debería reducir entre 5K y 6K, aproximadamente.

Muy amablemente, el jugador Looks me quiso colaborar con eso, él tiene casi las mismas estadísticas que yo, por lo que no se verán grandes diferencias de daño. Yo cuento con 5011 de temple en full PvP, él está con 4934 (Ven, no hay casi nada de diferencia)...

Mis explosiones, que deberían causarle de 5K a 6K de daño, causan un daño de 7K, (por maestría) las de él un daño de 6K.
![explosion aullante contra 1](https://cloud.githubusercontent.com/assets/12435844/9720071/608a23b0-5550-11e5-962b-395f8b2454e8.png)
Como se puede ver, y lo dije anteriormente, el daño de las explosiones actualmente usando full PvP a un objetivo full temple, es insifnificante,  es algo minúsculo, aproximadamente un 14% el daño de explosión aullante se ve aumentado.

Ahora, con los abalorios [Nido del último dragón] y [Vórtice transfigurador de almas] la cosa cambia porque... 
![explosion aullante contra 2](https://cloud.githubusercontent.com/assets/12435844/9720143/fc7e0d18-5550-11e5-9b31-8bc64304f1e3.png)
El daño reducido al golpear a un jugador full temple oscila entre los 7K a 8K aproximadamente, el daño ahora mismo es de 12K, es demasiado para golpear a alguien que tiene temple...

![explosion aullante contra 3](https://cloud.githubusercontent.com/assets/12435844/9720175/71140dc6-5551-11e5-832c-542c962dad76.png)
Y el daño crítico, que debería estar entre los 13K a 15K... mete golpes de 26K (Me han llegado a golpear con golpes de 40K, 60K... incluso 75K... teniendo full temple)

Con todo ello se puede decir que el daño de explosión está algo pasado, y supera los límites cuando se ponen abalorios de maestría y crítico (y se ponen a spamear...)

No digo que arruinen la maestría, ello perjudicaría mucho a los dk dado que muchas facultades como Golpe de escarcha, o fiebre de escarcha se verían afectadas y estas no superan los límites de daño, modificar la maestría sería también modificar estas habilidades, que están bien.
(Aún con esto, los heal son inmatables... ya se hablará de esto después)

Agradecimientos: A Looks por tenerme paciencia y dejarse golpear.

PD: Haré esto con todas y cada una de las clases y sus habilidades rebasadas de daño y sanación.
PD2: Creo que este hechizo no tendría nada de malo si no hubieran dk que lo spamearan. :imp:

**Comment by gringold** [comment]
Podrías informar el bug de los brujos que matan con un solo skill ?

**Comment by Myst** [comment]
Reparado. Gracias.

**Comment by gringold** [comment]
De nada, pero yo no informé ese bug.
Los que yo inicié fueron los 399 y 398.

Saludos

2015-09-12 14:53 GMT-03:00 Myst notifications@github.com:
