### ISSUE TITLE
Nido del último dragón 25n

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#405]
Reporte de bugs.
## Abalorio: Nido del último dragón.

Nido del último dragón es un abalorio para clases melee, otorga fuerza y golpe crítico dependiendo de el nivel de banda en el cual se haya sacado.
Lo que sucede, es que este abalorio, en 25, está bugueado, dado que su tiempo de estar activo es infinito, es decir, no se acaba. (Serie de imágenes)

![abalorio - nido del ultimo dragon](https://cloud.githubusercontent.com/assets/12435844/9834206/5e3aaace-5976-11e5-80f3-dabe581598af.png)

Hablo de ese nido.

Pondré el cronómetro por un minuto y revisaré a ver cuándo se acaba su efecto... (Nunca mientras siga golpeando)

![wowscrnshot_101215_174627](https://cloud.githubusercontent.com/assets/12435844/9834214/de246fea-5976-11e5-91ef-89bcb41abadb.jpg)
![wowscrnshot_101215_174717](https://cloud.githubusercontent.com/assets/12435844/9834215/de28996c-5976-11e5-933b-b8cffb6c6a82.jpg)
![wowscrnshot_101215_174736](https://cloud.githubusercontent.com/assets/12435844/9834216/de2b80dc-5976-11e5-8a1f-739c4b35ec8b.jpg)
![wowscrnshot_101215_174743](https://cloud.githubusercontent.com/assets/12435844/9834217/de2eb734-5976-11e5-8003-3ae95a23906a.jpg)
![wowscrnshot_101215_174753](https://cloud.githubusercontent.com/assets/12435844/9834218/de30fcd8-5976-11e5-8baa-5d24ff3ee218.jpg)
![wowscrnshot_101215_174802](https://cloud.githubusercontent.com/assets/12435844/9834219/de368bda-5976-11e5-8c37-ee2097fa470b.jpg)

Bien, su efecto jamás desapareció, y me otorgaba esa suma de golpe crítico eternamente.
De por sí esto ya es malo, es aprovecharse de el abalorio, pero lo peor es que clases que ni siquiera son melee fuerza las usan: He visto brujos, magos y cazadores usando este abalorio (sobre todo estos últimos). 
El abalorio le hace falta su tiempo de reutilización, que es de dos minutos.

**Comment by Myst** [comment]
Reparado.
