### ISSUE TITLE
Puntos de combo adicionales

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#406]
Reporte de bugs.
Clase: Pícaro.
## Talentos: Sutileza - Combate.

Los puntos de combo permiten el lanzamiento de determinadas facultades, dependiendo de qué tanto se acumulen (Hasta un máximo de 5).
No entraré en el tema de "Remates del pícaro en qué gastar sus puntos de combo"... Hablaré de que algunas habilidades que deberían dar sólo 1 punto de combo, están dando de a más.

Me explicaré: Los puntos de combo son esenciales en la rotación del pícaro, pero la forma desmesurada como los consiguen los ponen en una situación ventajosa (más de la que ya tienen con todos sus stuns y efectos... -Además del daño elevado, ya hablaré de eso después-). Revisaré cada habilidad generadora de puntos y veremos cómo rápidamente consiguen 5 puntos con sólo dos o tres ataques básicos (No cuentan los que abren sigilo como emboscada o golpe bajo, hablo de aquellos ataques que exclusivamente deberían generar 1p de combo)
- Hemorragia.

![habilidad picaro - hemorragia](https://cloud.githubusercontent.com/assets/12435844/9834694/677f2914-598c-11e5-8c8b-c3cc0ef2f008.png)
Cito textualmente: "Otorga 1p de combo".
... ¡1p de combo!

![hemorragia 1](https://cloud.githubusercontent.com/assets/12435844/9834704/d21f636a-598c-11e5-8fa9-08c68cf18818.png)
Aparte del exceso de daño que se ve en la imagen, de una sola hemorragia le he sacado 2 puntos de combo, es decir que si hacemos un recuento de la rotación general del pícaro de un golpe bajo y una hemorragia puede llenar instantáneamente sus 5 puntos de combo. 
Cito de nuevo: "...1p de combo", es la cantidad que debería dar.
- Puñalada.

![punalada 1](https://cloud.githubusercontent.com/assets/12435844/9834715/52b5e94a-598d-11e5-93b0-63a359c4e733.png)

La misma historia que con hemorragia, (aparte de su exceso de daño) es el hecho que debe dar sólo 1p de combo y esta da dos... 
- Golpe siniestro.

Post =  https://github.com/Myst/Bugtracker/issues/111

Ya había hecho este post, así que lo reposteo. x)

No hay ningún talento, ni habilidad que otorgue a estas facultades añadir 2p de combo instantáneamente, eso es imposible (exceptuando [Golpe siniestro], que con su glifo tiene un 20% de probabilidad de dar otro punto de combo, de hemorragia y puñalada NO) y, actualmente eso de dotar al pícaro con estas facultades de 2p de combo es bug.
Reitero, ¡sólo 1p de combo deben dar!

**Comment by Myst** [comment]
Reparado.
