### ISSUE TITLE
Arañazo

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#409]
Reporte de bugs.
Clase: Druida.
## Hechizo: Arañazo.

Arañazo es una de las facultades principales en la rotación del druida, aplica un efecto minúsculo de sangrado a la vez que genera puntos de combo (como un pícaro) que le permite lanzar otros ataques como Mordedura feroz o Destripar.

A continuación mostraré mi druida, su equipo, estadísticas y el daño que arañazo ejerce a objetivos SIN temple. Como siempre uso el addon Dr. Damage.

![aranazo 6](https://cloud.githubusercontent.com/assets/12435844/9978798/28a4b370-5f0f-11e5-88ea-55c559f22f29.png)

Como pueden ver, mi druida tiene un equipo implacable, con unas estadísticas medianamente despreciables. Aún así, arañazo es una habilidad que desfasa su daño sin importar el equipo.

Arañazo no se le puede aplicar a los muñecos de entrenamiento, así que pasaré directamente a aplicarlo en un jugador.

![aranazo 1](https://cloud.githubusercontent.com/assets/12435844/9978676/c86b8276-5f05-11e5-8dc4-80ac7fd27985.png)

Arañazo debe quitar un daño de 3281 a objetivos SIN temple... Con la reducción otorgada por el temple y la armadura de los pj su daño se vería reducido de un 45 a 50%, eso sería aproximadamente desde 1476 a 1640... En la foto se ve que quita 5347. Comparada con el daño que debe recibir el objetivo que es de 1476... 5347 es aproximadamente un 360% más... (Inclusi quita más de los 3K que debería quitarle a objetivos sin temple)
Ahora se dirá "Pero destrozar aumenta el daño de sangrados". Bien, observemos:

![aranazo 2](https://cloud.githubusercontent.com/assets/12435844/9978695/35692076-5f07-11e5-8a20-0fd87ccb8db8.png)

A un objetivo sin temple debería afectarle un daño de 4265, la reducción de daño lo dejaría en 2K aproximadamente. Como ven, el daño aumentado de destrozar sí funciona, pero arañazo es una habilidad que está bug, su daño es excesivo. Y eso que es un druida implacable, los cataclísmicos son peores. :disappointed: 

![aranazo 3](https://cloud.githubusercontent.com/assets/12435844/9978709/5fcb764c-5f08-11e5-8761-c353c7287945.png)

Hay cierto abalorio que potencia la maestría de las clases. El [Vórtice transfigurador de almas] es el abalorio predilecto de muchos druidas, con él pueden buguear arañazo a niveles impresionantes.

![aranazo 4](https://cloud.githubusercontent.com/assets/12435844/9978716/b6a8ea1c-5f08-11e5-98da-7c8388c7ac58.png)

Con la reducción de daño otorgada por el temple, este hechizo debería quitar 2.5K aproximadamente. Como se puede ver en la foto, quita 12K, no es necesario sacar un porcentaje para saber que es muchísimo.

![aranazo 5](https://cloud.githubusercontent.com/assets/12435844/9978725/3355dd04-5f09-11e5-8a12-4aef3f104ed5.png)

Y aquí su daño crítico... Donde le debería quitar a un jugador 5K aproximadamente, quito 24K.

Como se ve, un druida implacable ejerce un daño extremadamente inmenso, un cataclísmico es peor. El daño de esta habilidad está muy, muy por encima de lo normal, un bug que urge repararse.

**Comment by Myst** [comment]
Reparado. Gracias por el reporte.
