### ISSUE TITLE
[Banda] Ulduar: NPC bugs

### ISSUE THREAD

**Issue by gringold** [Myst/Bugtracker#411]
Informe de errores: 
Tipo: [Banda] Personajes bug
## Lugar: Ulduar ( http://es.wowhead.com/zone=4273/ulduar )

El bug es el siguiente: Al ingresar a la banda, luego de subirse a los tankes que se utilizan para matar unidades mas rápido; al intentar eleminar los personajes "Defensor de forja de acero", los mismos quedan en 1 hp de vida y luego no se los puede seleccionar mas, pero ellos siguen golpeándote, lo que hade muy muy molesto continuar con la banda. 

Dejo el link del pnj que encontré el wowhead, difiere el nombre al parecer pero es ese: 
http://es.wowhead.com/npc=33572/defensor-de-acero-forjado

También dejo una captura de pantalla donde se puede comprobar el bug:
![ulduar 01](https://cloud.githubusercontent.com/assets/13881808/10125438/89e7869e-654a-11e5-8269-a793b50d52c4.png)

Saludos.

**Comment by gringold** [comment]
Esto se soluciono con la nueva actualizacion de servidor. 
Cierro el ticket.
Saludos.

**Comment by gringold** [comment]
Reabro, lamentablemente con la echada hacia atrás de la actualización del server esto se vuelve a producir

**Comment by Myst** [comment]
Reparado.
