### ISSUE TITLE
GENESISx6-Ingenieria e Alquimia bug

### ISSUE THREAD

**Issue by Cimeries** [Myst/Bugtracker#424]
Buenas,hay un grave inconveniente con la Profesion Ingenieria(digo "GRAVE" ,porque se supone que uno la levea para obtener las mejoras 525 y con ingenieria solo se pueden hacer "garabatos",quedando esta profesion "OBSOLETA" al 100%)
A continuacion les comento las mejoras y descubrimientos bug:

MEJORA:  http://es.wowhead.com/spell=126734/muelles-de-sinapsis
EFECTO: El uso de esta mejora aumenta la estadistica mas elevada 480puntos(intelecto,agilidad o fuerza) en mi caso tendria que ser fuerza.
INCONVENIENTE: No eleva ninguna estadistica.

ANTES DE ACTIVARSE
![image](https://cloud.githubusercontent.com/assets/12799485/10417141/28ebf61c-6fff-11e5-9f0f-37f422f33134.png)
LUEGO DE ACTIVARSE
![image](https://cloud.githubusercontent.com/assets/12799485/10417363/adfb0a76-7006-11e5-9023-e831fbd9dc24.png)

MEJORA:  http://es.wowhead.com/spell=82626/escudo-de-plasma-con-toma-de-tierra
EFECTO: Activan un escudo que absorbe 18k  de daño.
INCONVENIENTE: No se activa nada,no hay buff,sonido,nada.
![image](https://cloud.githubusercontent.com/assets/12799485/10417160/f89b8f62-6fff-11e5-995c-2811d53911be.png)

MEJORA: http://es.wowhead.com/spell=84424/campo-de-invisibilidad
EFECTO: Se aplica al cinturon para volverte invisible cuando no estas en combate.
INCONVENIENTE: Al activarse no sucede nada.
![image](https://cloud.githubusercontent.com/assets/12799485/10417207/bfb76a26-7000-11e5-82ee-a33f9fd84cea.png)

DESCUBRIMIENTOS DE INGENIERIA: Al llegar al nivel 525,se puede descubrir 8 mejoras(que no son aprendidas con el instructor de profesion)sino fabricando http://es.wowhead.com/item=59364/machacapollos-derrotado ,al fabricarlos el ingeniero tiene el 100% de probabilidad .de aprender nuevas mejoras.
![image](https://cloud.githubusercontent.com/assets/12799485/10417247/b05c581e-7002-11e5-92b2-24cf1bc0adbf.png)
En esta imagen se ve que tengo fabricado 6 machacapollos y solo he descubierto 3(tres) mejoras,fuera de las que se aprenden con los instructores.
![image](https://cloud.githubusercontent.com/assets/12799485/10417250/ee7450ac-7002-11e5-8281-1b4cc4534b5f.png)

ALQUIMIA
HECHIZO: http://es.wowhead.com/spell=78866/convertir-elementos-vivos
EFECTO: Convierte 15-16  vidas volatiles en elementos volatiles aleatorios y ademas si eres 
http://es.wowhead.com/quest=29482/maestro-de-transmutacion    tienes una posibilidad de obtener  volatiles aleatorios extras.
INCONVENIENTE: En la expansion Cataclismo,se modifico el hechizo de convertir elementos vivos,pudiendo uno trasladarse a las zonas asociadas con los planes elementales,y logrando asi convertir de acuerdo en que zona esta(mas abajo comentario de un azul) y esto no sucede en GenesisX6.Tambien el inconveniente es el elemento aleatorio extra por ser maestro en transmutacion no lo da.

![image](https://cloud.githubusercontent.com/assets/12799485/10417337/34e61310-7006-11e5-9475-88be22c1172d.png)

![image](https://cloud.githubusercontent.com/assets/12799485/10417340/3e18d7d8-7006-11e5-8359-c03acef4f9ac.png)

PD:Myst,vuelve el sv como estaba.

Slds.

**Comment by gringold** [comment]
Hola Cimeries. 
Cabe aclarar que siendo dk, al conectarse la salud está bugueada, hay que cambiar de auras para que vuelva a la normalidad, esto es menor. 

Pero hay skills como Cuerno del invierno (http://es.wowhead.com/spell=57330/cuerno-de-invierno), que no suman la fuerza ni la agilidad que deberían. 
Por otro lado se bajó excesivamente el daño de Golpe Letal ( http://es.wowhead.com/spell=49998/golpe-letal ), a mi parecer no está procediendo correctamente el pasivo Aroma de Sangre ( http://es.wowhead.com/spell=49509/aroma-de-sangre ) el cual incrementa su daño un 20% mas. 

Si a ti también te está sucediendo esto Cimeries por favor hásmelo saber. 
P/D: No soy ingeniero, por eso no puedo ayudarte con tu problema
Saludos.

**Comment by gringold** [comment]
Si necesitas aire volatil Cimerires puedes farmearlo de las arañas en Tol Baral, ahora dropean mucho aire, fuego y agua volatil yo junté unos 250 en poco menos de una hora. 
Espero te sirva.
Saludos.
