### ISSUE TITLE
instancias

### ISSUE THREAD

**Issue by Enfermera** [Myst/Bugtracker#426]
No se puede ingresar a tierra de fuego ni a alma de dragon en ningun modo de banda (10-25) dice q para ingresar debe estar de nivel 85

**Comment by gringold** [comment]
Confirmo que también arroja el mismo error en Bastion del Crepúsculo. 
Por otro lado el contenido viejo parece estar arreglado.

**Comment by gringold** [comment]
El mismo mensaje que informa enfermera pero con la diferencia de que dice "Se requiere al menos level 83 para ingresar a esta instancia", lo arroja el juego al tratar de entrar a Grim Batol también.
