### ISSUE TITLE
bonus set

### ISSUE THREAD

**Issue by Enfermera** [Myst/Bugtracker#427]
no se dan los bonus q dice en los set cataclismo, ni el bonus de temple, intelecto ni los beneficios q dan por tener 4 partes de ese mismo set

**Comment by Myst** [comment]
Reporta porfavor los links de los sets en cuestión.

**Comment by Enfermera** [comment]
Me imagino q son todos los bonus de los set`s cataclismo del juego pero pondre los de malla q son los q mas me interezan XD http://es.wowhead.com/transmog-set=1232/cataclysmic-gladiators-earthshaker
