### ISSUE TITLE
Gemas y piedras epicas en bolsas para guardar gemas

### ISSUE THREAD

**Issue by Enfermera** [Myst/Bugtracker#428]
ninguna gema ni piedras epicas q salen en las geodas de elementiun se pueden guardar en ninguna bolsa de gemas, http://es.wowhead.com/spell=100585/bolsa-de-gemas-de-seda-lujosa como por ejemplo

**Comment by Myst** [comment]
Reparado el que reportaste., debes reportarlos uno por uno porfavor.

**Comment by Enfermera** [comment]
no se a reparado esta bolsa aun no pudo meter gemas ni piedras epicas sacadas de las geodas de elemetium http://es.wowhead.com/item=67392/agarre-con-tachuelas-de-gemas-trasportin-exclusivo

http://es.wowhead.com/spell=100585/bolsa-de-gemas-de-seda-lujosa
