### ISSUE TITLE
BUG DE LA MAESTRIA EL EL BRUJO

### ISSUE THREAD

**Issue by anarosa0902** [Myst/Bugtracker#432]
Saludos. quiero reportar este bug ya que la maestria es la mañor fuente de el daño para en brujo en cualquiera de sus ramas

en estas imagenes le mostrare el equipo que utilizo con el brujo, con ayuda del addon Dr. Damage demostar el daño que deberia hacer la facultad Mano de Gul´dan (Que deberia ser la facultad que mas daño hace) y que no cambia en nada al agregar o quitar maestria a las estadisticas

http://es.wowhead.com/spell=105174/mano-de-guldan (cabe destar que wowhead no hace referencia al hechizo en la expansion 4.3.4 asi que no creo que este link pueda hacer referencia pero igual lo coloco)

En esta imagen muestro al brujo con equipo pvp menos la daga.

![equipo full pvp](https://cloud.githubusercontent.com/assets/15090549/10441898/c1013746-7117-11e5-91f4-adcc402fa16f.jpg)

Aqui muestro el daño de Mano de Gul´dan con este equipo pvp.

![critico full pvp](https://cloud.githubusercontent.com/assets/15090549/10441932/0225dca4-7118-11e5-8391-33d51ecbdb1b.jpg)

 Como podran ver el critico fue de mas o menos 17k, Segun el addon Dr. Damage deberia ser una media de 25k o un critico de 51k.

Ahora me colocare el abalorio Vortice transfigurador de almas el cual aumenta mucho la maestria.
http://es.wowhead.com/item=77990/vortice-transfigurador-de-almas

![con el vortise](https://cloud.githubusercontent.com/assets/15090549/10441980/81cbcc2a-7118-11e5-916a-c571299f64e5.jpg)

Aqui puede leer el efecto que hace la maestria en el brujo y los 31 puntos que aumenta con el efecto del vortice activo.

Cabe destacar que con y sin el vortice el daño sigue en 18%.

![bufo del vortise](https://cloud.githubusercontent.com/assets/15090549/10442067/ee95c798-7118-11e5-8dca-ee86a79fe749.jpg)

y a continuacion les muestro el daño que hace el hechizo Mano de Gul´dan con el efecto del vortse activo.

![dps con el vortise](https://cloud.githubusercontent.com/assets/15090549/10442091/165a3692-7119-11e5-85bc-90b9ccb3ef0e.jpg)

Como podran ver el DPS es casi el mismo. segun el addon Dr. Damage. 

Lo cual es totalmente errado ya que que la maestria potencia el dps de manera exorbitante. Tambien debo mencionar que casi ningun golpe es critico.

En el servidor el brujo tenia hechizos bug que la mestria potenciaba. Pero antes de la actualizacion habian arreglado dichos bug y habia un dps aceptable.

Cabe mencionar que en otras clases como lo es el mago. La maestria funciona perfectamante.

Sin mas que hacer referencia respecto a la maestria me despido y espero la arregle pronto.

**Comment by gringold** [comment]
jajajaja No pueden bugguear mas en la battleground ? jajajajajajaja

**Comment by Myst** [comment]
Lamentablemente 51k es un daño excesivo, hemos decidido equilibrar algunos hechizos, empezando por el que mencionas.

**Comment by anarosa0902** [comment]
Ok entiendo su punto. Pero estamos hablando de 51k a objetivos sin temple. Estoy deacuerdo que ciertos hechizos causaban un daño desproporcionado pero practicamente es como si la maestria estubiese en 0. Estamos hablando que el brujo queda descartado como clase dps en comparacion a otras clases y en todas sus ramas por igual. Valoro su trabajo pero el abalorio pve practicamente esta quedando como un adorno ya que no funciona para esta clase. Que fue lo que demostre en el reporte. Entiendo que deben regular muchos dps pero 17k a un muñeco de pruebas que quedara para objetivos con temple. Sin mecionar a los heler que se curan 100k. Me parece exagerado ya que no solo es la mano de gul,dan sino todos los hechizos de la clase en general.
