### ISSUE TITLE
BUG DEL DAÑO DEL SACERDOTE SOMBRA

### ISSUE THREAD

**Issue by anarosa0902** [Myst/Bugtracker#434]
En esta oportunidad quiero reportar el daño excesivo del sacerdote en su rama de talentos sombra.

Con la ayuda del Adoon Dr. Damage les mostrare el daño exorbitante de esta clase.

Aqui pueden aprecia el equipo de mi sacerdote sombra Es full implacable. Lo unico que tiene del set cataclismico es el arma.

![equipo](https://cloud.githubusercontent.com/assets/15090549/10442931/4b10482e-7121-11e5-80e0-19fe84fa7758.jpg)

Al probar el dps con el muñeco de pruebas y activar todos los cd podemos apreciar el cuadro que se encuenrta del lado inferior derecho es el Addon Dr. Damage. El daño medio y critico de lo que seria el hechizo. Explosion mental.
http://es.wowhead.com/spell=8092/explosion-mental

![dr damage](https://cloud.githubusercontent.com/assets/15090549/10442992/da8692f6-7121-11e5-9b61-987792119c8b.jpg)

 Segun el Dr. Damage el daño deberia ser una media de 38k y un critico de mas o menos 79k.

pero no es asi el resultado es el siguiente.

![wowscrnshot_101215_174243](https://cloud.githubusercontent.com/assets/15090549/10442999/0a90778c-7122-11e5-8ead-2ebd1fff371e.jpg)

Un critico d 107k (ha llegado pegar 120k e incluso 130k pero ese fue el capture que pude tomar)

Como veran esta demasiado por ensima de lo que deberia ser su dps normal y mas para solo poseer un set implacable con carencia de gemas epicas y encantamientos y ningun tipo de abalorio pve.

Saludos.

**Comment by Enfermera** [comment]
recuerda q en los muñecos de entrenamiento siempre va a ser mas alto el dps porq esos muñecos no tienen temple ni nada de so

**Comment by gringold** [comment]
Aunque no tenga temple, es un crítico altímisimo mi querida Enfermera. Si le restas a ese crítico el promedio de temple de un jugador que es un 40% aproximadamente, te quedaría un crítico de 64500.
Siguen siendo excesivo.

**Comment by gringold** [comment]
Además si leés la descripción vas a ver que es un set implacable, y sin gemas, ni encantamientos, ni albalorios. Me parece que tenés un sacer sombra Enfermera, porque de otra manera no podés estar tratando de desestimar el daño mostrado en las imágenes.

**Comment by Enfermera** [comment]
En estos momentos no tengo presente si tengo algún sacer pero solo es para tener en cuenta él daño q hace frente a un muñeco de entrenamiento y frente a un pj full cata, y si te fijas un poquitois reportes son para q arreglen en chamán q es él único pj con quien juego de resto no se q tal estén

**Comment by gringold** [comment]
Lo entiendo perfecto, por eso en mi post puse un calculo de como quedaría el crítico (aproximadamente) en un objetivo con un 40% de temple. Era una pequeña broma lo de que tenías un sacer sombra, ya que es lo mas común de ver en bg hoy por hoy en el server ( debido a que están bug ). 

Saludos :D

**Comment by Pullsee** [comment]
Perdona que te corrija pero diras nerfeado... Sera tu sacer o el muñeco pero mi sacer full cataclismica o full hc no pasa de los 11k con explo+3 orbes+ mastery alta... Tambien he probado con baja. Las pegatas (dots) quitan poco comparado con otros servers menos bugs al igual q en el ofi en la 4.3.4 . Posdata mi sacer es Piiruleta

**Comment by gringold** [comment]
Hola Pullsee. Publicá una captura de pantalla donde muestres que tu sacer pegue poco como decís. Y bien detallada. Hasta que no lo hagas se puede interpretar que no querés que te nerfeen y poder seguir bugueando libremente con el daño ridículo que vienen haciendo desde hace tiempo ya.
