### ISSUE TITLE
Gemas y piedras epicas en bosas de joyeria

### ISSUE THREAD

**Issue by Enfermera** [Myst/Bugtracker#435]
no se a reparado esta bolsa aun no pudo meter gemas ni piedras epicas sacadas de las geodas de elemetium http://es.wowhead.com/item=67392/agarre-con-tachuelas-de-gemas-trasportin-exclusivo

http://es.wowhead.com/spell=100585/bolsa-de-gemas-de-seda-lujosa

**Comment by Myst** [comment]
Reparado
