### ISSUE TITLE
geoda cubierta de elementium

### ISSUE THREAD

**Issue by Enfermera** [Myst/Bugtracker#436]
No se acumula por paquetes de 20 y dice q no tiene cargas http://es.wowhead.com/item=78891/geoda-cubierta-de-elementium

**Comment by Myst** [comment]
Hola, respecto a las cargas eso le ocurrió a quienes estuvieron abusando indiscriminadamente, de esta manera tus geodas ya no sirven y solo te queda descartarlas. Respecto a que no se acumulan, ya esta reparado y se aplicará en el siguiente reinicio, gracias por tu reporte.
