### ISSUE TITLE
DAÑO EXCESIVO CLASE CAZADOR

### ISSUE THREAD

**Issue by Cimeries** [Myst/Bugtracker#440]
Buenas,normalmente no abro dialogos sobre  PVP ,ya que no tengo mucho conocimiento del mismo.Pero realmente ya me irrita esto de los disparos de los cazadores.
No hay que hacer muchas sumas y porcentajes  para ver  el daño excesivo que estan haciendo y siempre hicieron,  en la imagen a continuacion muestro como de  dos disparos me bajaron 88.752.Por mas manco que pueda ser,tengo full temple,aguante,set cata y no soy un muñeco de entrenamiento.
![image](https://cloud.githubusercontent.com/assets/12799485/10577606/07859952-7643-11e5-96d7-057511c86d37.png)

Comento esto , ya que en issues anteriores se le hace caso OMISO al PVE,y se  "PRIORIZA" (SUPUESTAMENTE) al PVP.

PD:Favor alguien que sepa explicar lo mencionado con imagenes,addons,etc.,se lo agradeceria.

Slds.

**Comment by gringold** [comment]
Buenas Cimeries. 

Antes que nada, cuando te encuentres otra vez con el caza en cuestión ( ya que vi que como todo un señor censuraste su nombre de usuario ), revisá su inventario. 
Tené en cuenta que hay muchos albalorios bug en el juego. Al ver esos golpes críticos, yo revisaría si el caza no tiene el albalorio: "Nido de último dragón: http://es.wowhead.com/item=77205/nido-del-ultimo-dragon". Este albalorio si bien da fuerza, tiene chance aumentar muchísimo los puntos de golpe crítico por 20seg (lo cual hace que peguen mas criticos y mas fuerte), el mismo se encuentra bug ya que esta chance siempre procede, lo que hace que el daño ya bug de cazas, brujos y sacerdotes sombra se exponencie. He visto muchos pjs de éstas especializaciones que aunque no se vean beneficiados por la fuerza usan este albalorio debido a que esta bug. 
Teniendo en cuenta que te metieron 3 críticos seguidos con tanto daño ( menos mal que absorbiste uno jaja ) no me extrañaría que tuviera dicho albalorio.

Además de esto, también es probable que haya activado a través de una macro dos albalorios que comparten CD al mismo tiempo ( sólo debería poder activar uno y no ambos a la vez, pero con una macro buguean ), boosteando desmesurablemente su agilidad y daño. 

Además, es daño de naturaleza el crítico mas fuerte y si el caza se gemeó con penetración de hechizo ( que es lo mas aconsejable para pvp ) es probable que haya ignorado tu temple aunque no estoy seguro.

Saludos.

**Comment by gringold** [comment]
Buenas otra vez. 
Según aseguró Myst en este post viejo: https://github.com/Myst/Bugtracker/issues/405
El albalorio nido ultimo dragón que mencioné estaría reparado. 

Asi que es posible que estén bugueando con otra cosa ahora jajaja.

Saludos.

**Comment by Myst** [comment]
Reparado.
