### ISSUE TITLE
Maestría bug - Sacerdotes sagrado

### ISSUE THREAD

**Issue by MjOmeteuhtli** [Myst/Bugtracker#441]
MAESTRÍA – ECO DE LUZ
La maestría hace que los hechizos de sanación directa sanen un 11% de lo sanado durante 6 segundos, aumentando 1.25% por punto en maestría.
![4](https://cloud.githubusercontent.com/assets/14099660/10569473/17eabba8-75ec-11e5-8874-2e907a4211c2.jpg)
Teniendo esta maestría: (8.00+1.58)
![5](https://cloud.githubusercontent.com/assets/14099660/10569481/3e1536fa-75ec-11e5-8e3e-1fc73a89e85f.jpg)
Estos son los resultados:
![6](https://cloud.githubusercontent.com/assets/14099660/10569492/54881222-75ec-11e5-8af7-a01bd72f307e.jpg)
Una sanación relámpago de 17601, con la sanación de la maestría total de: 1936 x 6 = 11616. Esto es una sanación adicional por maestría de casi 66%, cuando la sanación adicional por maestría debería ser: [ 11% + (1.58 x 1.25%) ] = 12.98% , teniendo así un excedente del 53% de sanación, lo que es DEMASIADA VENTAJA.
Acá una foto de otro server dónde funciona más o menos bien (maestría 8.00+1.27):
![7](https://cloud.githubusercontent.com/assets/14099660/10569500/6a6459e8-75ec-11e5-959a-152b143fb1b2.jpg)
Una sanación relámpago de 16473, con sanación por maestría de 320 x 6 = 1920 , lo que es un 11.65% de sanación por maestría, que está muy cerca de la fórmula de la maestría  [ 11% + (1.27 x 1.25%) ] = 12.58% .
CONCLUSIÓN: La maestría de los sacerdotes sagrados les otorga UNA VENTAJA VISIBLE Y DEMASIADO GRANDE, teniendo una curación adicional del 53% por cada cura que se metan, por ello se trata de un CASO URGENTE, que afecta demasiado el pvp en el server.

**Comment by Myst** [comment]
link?

**Comment by MjOmeteuhtli** [comment]
http://es.wowhead.com/spell=77485/maestria-eco-de-luz

**Comment by Myst** [comment]
Reparado, gracias por el reporte.
