### ISSUE TITLE
Problema con zona Huargen

### ISSUE THREAD

**Issue by v960** [Myst/Bugtracker#442]
No estoy seguro de si solo me paso a mi, pero al llegar a la zona de Gilneas post-tutorial, no hay NPC, no hay enemigos y es imposible progresar en esa area ya que las puertas estan cerradas y no se puede ir mas allá sin misiones.

**Comment by Myst** [comment]
Recuerda que gilneas post-tutorial es una ciudad que ha sido atacada por los no muertos.
