### ISSUE TITLE
Quest mala en durotar

### ISSUE THREAD

**Issue by migueluchon** [Myst/Bugtracker#443]
No se puede usar el objeto de la mision perdentryos en el desbordamiento el objeto es catalejo de thonk para localizar unos nps

**Comment by Myst** [comment]
Porfavor coloca el nombre correctamente junto con el link de wowhead.

**Comment by migueluchon** [comment]
Porque tengo que hacer la mitad del trabajo que se supone que uds tienen que hacer? e.e

**Comment by Myst** [comment]
Son las reglas del bugtracker, y no se supone que nosotros debemos hacerlo, se supone que el servidor es donde tú juegas y si quieres que mejore debes poner de tu parte.
