### ISSUE TITLE
Menas de cobre bugueadas

### ISSUE THREAD

**Issue by migueluchon** [Myst/Bugtracker#444]
las menas de cobre aparecen en el aire y son imposibles de recolectar igual he visto que pasa con algunas raíces esto me pasa en durotar

**Comment by Myst** [comment]
porfavor coloca que menas de cobre tienen este problema

**Comment by migueluchon** [comment]
Como se supone que yo vaya a saber eso e.e ya dije que es en durotar

**Comment by Myst** [comment]
Fotos.........
