### ISSUE TITLE
Buscador de mazmorras.

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#445]
## Reporte de bugs

World of Warcraft se compone de dos ámbitos que hacen una experiencia de juego magnífica: Por una parte está el PvP (Player vs Player), que es enfrentarse a muerte a los jugadores; por otra está el PvP (Player vs Environment) que es jugar con los elementos del ambiente con los que está abrazado el juego y uno de los más importantes son: Las mazmorras.

Las mazmorras son lugares fortificados donde grupos de cinco personas se preparan para luchar contra el entorno que le presenta el juego, desde enfrentar muchos bichos hasta matar un boss para obtener recompensas formidables o logros únicos. Hay dos modos de llegar a una mazmorra: o bien armar el grupo de cinco y buscar la entrara para acceder a ella, o usando una herramienta bastante útil que es: El buscador de mazmorras.

Una de las herramientas más usadas es el buscador de mazmorras, y sirve para de entre todos los jugadores, unir cinco y ponerlos a enfrentar una de las muchas mazmorras que hay enlistadas. (Depende de la expansión, el nivel del personaje, el nivel de equipo y la estabilidad del server respecto al funcionamiento de sus mazmorras... No ahondaré en eso)

El buscador de mazmorras funciona de una manera muy similar (por no decir igual) a los campos de batalla, simplemente se busca el ícono del buscador (el ojo verde) se selecciona la función (todo con respecto a la clase que se sea), y se selecciona "encontrar grupo"... Cuando todas las funciones estén listas, el buscador teletransportará automáticamente a todos los miembros de grupo a la mazmorra indicada (o de forma aleatoria si lo escogieron así)

![buscador de mazmorras](https://cloud.githubusercontent.com/assets/12435844/10713080/d867f328-7a74-11e5-8248-5533210791ec.png)

El problema es que está totalmente inservible. Ni siquiera sale su ícono buscando a otras personas para unir grupo y hacer las mazmorras. Esta herramienta es muy atractiva para quienes gustamos del PvE y actualmente está inservible.

**Comment by Myst** [comment]
Hola, de hecho si funciona, la única que esta funcionando es la opción de buscar mazmorra aleatoria de hora de crepúsculo las demas funcionan bien :)
