### ISSUE TITLE
Sangre del norte

### ISSUE THREAD

**Issue by Salinger2010** [Myst/Bugtracker#446]
Reporte de bugs.
Clase: Caballero de la muerte.
## Talento: Escarcha.

![sangre del norte 1](https://cloud.githubusercontent.com/assets/12435844/10713095/52839d56-7a75-11e5-8da7-346a5341ec9c.png)

Los caballeros de la muerte en escarcha tienen la facultad [Sangre del norte] que permite convertir sus runas de sangre en runas de muerte de manera permanente -como se ve en la foto-. Esto le permite al dk usar sus ataques principales en su rama como Asolar, explosión aullante o cadenas de hielo.

El problema es que al gastar una de esas runas se convierte en runa de sangre, eso NO debe pasar.

![sangre del norte 2](https://cloud.githubusercontent.com/assets/12435844/10713103/a94f521a-7a75-11e5-89d4-f83fcdd1f05a.png)

En la foto se ve cómo mi runa pasa de ser de muerte a ser de sangre. Esto limita mucho los ataques del dk ya que se verá forzado a usar una runa para ataques prácticamente inservibles.

**Comment by xxspokiixx** [comment]
Tienes activado el talento de unholy en vez del de escarcha segun las imagenes que muestras. La primera barra , tienes Sangre,escarcha y unholy , y claramente se ve seleccionado Unholy ademas de que en la parte de buff se ve tmb unholy.

Saludos
