### ISSUE TITLE
El server mas bugueado en el que he jugado

### ISSUE THREAD

**Issue by migueluchon** [Myst/Bugtracker#447]
Casi todas las misiones tienen bugs desde durotar y baldios del norte hasta vallefresno.
-No aparecen los Npc's muchos de los Monstruos con los que tengo que luchar para recolectar objetos de misiones no me dan nada, si tengo que usar un objeto de misión no me deja usarlo, etc etc etc.... 

Les propongo a todos los admin de este server que empiecen a jugar con cada raza y clase que hay, almenos la raza y veran el sin fin de errores que hay. Como esperan que los votemos como los mejores si ni siquiera se toman el tiempo de leer esto?.

si es que les molesta porque no me dejan migrar a otro server con menos errores y mas atención como monster wow, que decepción.....

**Comment by gringold** [comment]
Que ?? No se de que bugs hablás men. Convidá de lo que fumas.
