### ISSUE TITLE
MAMUTEO EN HORAS DE LA MAÑANA

### ISSUE THREAD

**Issue by Cimeries** [Myst/Bugtracker#453]
Buenas,normalmente no denunciaria a PJs si veo que mamutean,pero tengo conocimiento que hay eventos mensualmente en el indice 2c2 y 3c3 y hay premios.
En fin,mi denuncia va para los equipos: "Naranja y Plancks"  y "Cocacola y Micturas",este equipo "Cocacola" hasta en visto que esta en 2°lugar en el Top Arenas Teams
Adjunto fotos,son todas las mañanas en las imagenes se ve el horario del server.

"Naranja y Plancks"
![image](https://cloud.githubusercontent.com/assets/12799485/10732750/42f6c7bc-7bda-11e5-9dc6-4d1e90abc1d9.png)
![image](https://cloud.githubusercontent.com/assets/12799485/10732777/5d94c74a-7bda-11e5-89c5-3ce0a8da0bd8.png)
![image](https://cloud.githubusercontent.com/assets/12799485/10732786/69dfde40-7bda-11e5-8c6f-c5b101f9501f.png)
![image](https://cloud.githubusercontent.com/assets/12799485/10732790/7537bdbc-7bda-11e5-80b0-02787de10efd.png)

"Cocacola y Micturas"
![image](https://cloud.githubusercontent.com/assets/12799485/10732821/996642a8-7bda-11e5-8c6b-996bf90ac0e5.png)
![image](https://cloud.githubusercontent.com/assets/12799485/10732832/aa966a26-7bda-11e5-8182-157b289ea872.png)

**Comment by MjOmeteuhtli** [comment]
Luego de comprobación, pjs baneados, gracias por la información.
