### ISSUE TITLE
nivelen las clases si quiera eso hagan 

### ISSUE THREAD

**Issue by kevin55555** [Myst/Bugtracker#454]
los palas pegan y se curan demasiado los brujos demoneologuia sacan demaciado con pisoton es mas todo anda bug en este server horrible no hay como jugar mas migro de monster aca que feo tomar esa decision

**Comment by Myst** [comment]
Nuevamente este es el lugar para reportar los errores de juego, siguiente el formado especificado en la página princiapl.
