### ISSUE TITLE
Disparo de punteria (cazador)

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#49]
https://wow.freakz.ro/spells.php?spell=82928 Spell con daño de 22k al instante y con Cd (combos) En realidad este daño que hace tal como lo dice el link que deberia estarpegando 1371 hasta 4111 de daño y con criticos de 14.5 hasta 16.3k.

**Comment by Salinger2010** [comment]
De hecho, [Disparo de puntería, está sacando el daño que debe. Debes tener en cuenta la reducción de daño que genera la armadura y el temple. Pero a objetivos comunes, éste hechizo logra dar buenos resultados. (Quizá demasiados)

![disparo d epunteria](https://cloud.githubusercontent.com/assets/12435844/8896012/f8e539c4-33b3-11e5-90a4-e54468245cc6.png)
