### ISSUE TITLE
Filotormenta (Guerreros)

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#53]
http://es.wowhead.com/spell=69652/filotormenta Hechizo de los wars Que en donde su daño normal deberia estar en 9k y sus criticos deberian poder alcanzar los 20k

**Comment by Salinger2010** [comment]
Ignoras la reducción de daño generada por el temple y la armadura, además que también depende del equipo que posea el guerrero. Mi guerrero (implacable) saca de 27 - 30K con este poder (sin cd)

![filotormenta](https://cloud.githubusercontent.com/assets/12435844/8896039/dc47a292-33b4-11e5-9ece-10ff7c3bb60f.png)
