### ISSUE TITLE
Aburmar (Guerreros)

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#54]
http://es.wowhead.com/spell=24407/abrumar
http://es.wowhead.com/spell=65924/abrumar
Su daño esta muy bajo que en donde los wars sacan poco daño ademas su daño deberia estar sacando entre 2.8k hasta 3.6k de daño.

**Comment by Salinger2010** [comment]
Ignoras que el temple y la armadura, ayudan a que se reduzca el daño a los objetivos jugadores. En los links no se muestra esa reducción, pero sí el daño. Aquí tienes el daño.

![abrumar](https://cloud.githubusercontent.com/assets/12435844/8896057/62ece3d4-33b5-11e5-8826-23bd8c321072.png)
