### ISSUE TITLE
Temeridad

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#56]
http://es.wowhead.com/spell=1719/temeridad el daño que otorga esta en 50% pero debe ser en el 60%

**Comment by Salinger2010** [comment]
No otorga daño, otorga probabilidad de golpe crítico con ataques especiales del guerrero (Véase: Abrumar, Golpe mortal, Sed de sangre o embate) En la expansión cataclysm, éste hechizo debe otorgar un 50% más de golpe crítico, y un 20% más de daño recibido.

![habilidad guerrero tremeridad](https://cloud.githubusercontent.com/assets/12435844/8896093/a416c040-33b6-11e5-8d02-565069988051.png)
