### ISSUE TITLE
Mascota bugs al entrar a Campos de batalla.

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#57]
Bueno no hay link ni foto pero especificare el problema que tiene muchos cazas:
Una vez que se anota y se entra a  los campos de batallas la pet desaparece y se borra la tratamos de invocar y nada es decir se desapareció del todo y hasta toca ir a buscarla y domarla de nuevo y volver a repetirlos pasos.

**Comment by Myst** [comment]
Esto ya debería estar reparado.
