### ISSUE TITLE
Paladin Tanque

### ISSUE THREAD

**Issue by Psytrance** [Myst/Bugtracker#62]
La facultad no funciona como debería ya que con 3 cargas de poder sagrado mas abalorios mas cds no baja mas de 10 u 12 mil como máximo  critico siendo full cataclismico
http://cata.openwow.com/spell=53600
atte Psytrance del Genesis

**Comment by Myst** [comment]
Porfavor instala el addon dr damage y compara el daño con causado con el la media.
