### ISSUE TITLE
Sagrario Interno Sacerdote (BUG)

### ISSUE THREAD

**Issue by RokkanJC** [Myst/Bugtracker#64]
Talento: Sagrario Interno 3-2-1 http://cata.openwow.com/spell=14771

Bug: No otorga el beneficio de reduccion de daño de hechizo de Fuego interno de 2%/4%/6%/ pero si otorga bonus de movimiento de 6% mas en el personaje con Voluntad interna

**Comment by Myst** [comment]
Reparado en el siguiente reinicio.
