### ISSUE TITLE
Pestañas de guild 

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#66]
Las pestañas de la guild de lvl 25 que al comprarlas con estos permisos se borran como si nada y no se dejan comprar 
http://es.wowhead.com/item=62286/vale-de-camara-de-hermandad-7-ranura
http://es.wowhead.com/item=62287/vale-de-camara-de-hermandad-8-ranura

**Comment by Myst** [comment]
Funcionan correctamente.
