### ISSUE TITLE
Glifo de polimorfia [Mage] [ ID:56375]

### ISSUE THREAD

**Issue by dreyzar** [Myst/Bugtracker#75]
No esta removiendo los daños en tiempo del objetivo que se le aplica polimorfia, mucha desventaja para un mago el que no pueda Ccear.

http://cata.openwow.com/spell=56375

Saludos Dragneell :3

PD: los bugs reportados de mago son los mas esenciales, hay muchas mas proc´s bugs pero no son tan importantes como estos.

**Comment by Myst** [comment]
reparado.
