### ISSUE TITLE
Glifo de reflejo exacto [Mage] [ID:63093]

### ISSUE THREAD

**Issue by dreyzar** [Myst/Bugtracker#76]
Al tener activado este glifo los clones deberian hacer un 25% extra de daño ya que lanzarian hechizos de la misma rama en la que esta el mago, actualmente no lo hace.

http://cata.openwow.com/spell=63093

PD: los bugs reportados de mago son los mas esenciales, hay muchas mas proc´s bugs pero no son tan importantes como estos.

**Comment by Myst** [comment]
La descripción del link no dice nada acerca de aumentar el daño.
