### ISSUE TITLE
Piro explosion daño incorrecto [Mage Fire]  [ID: 11366]

### ISSUE THREAD

**Issue by dreyzar** [Myst/Bugtracker#78]
El coeff de daño de piroexplosion esta mal, aca una imagen del daño que deberia hacer correctamente y el daño que esta haciendo...

actualmente hace un daño de 17k no crit y deberia hacer 21k si tuviera el coeff correcto (claro testeado con mi SP)

http://www.subeimagenes.com/img/pyro-1306570.jpg

testeado con Dr.Damage version 4.3.4

http://cata.openwow.com/spell=11366

Solo el daño del piroexplosion al castear esta bajo el instantaneo esta bien

**Comment by Myst** [comment]
Reparado.
