### ISSUE TITLE
Bola de fuego daño incorrecto [Mage Fire] [ ID: 133]

### ISSUE THREAD

**Issue by dreyzar** [Myst/Bugtracker#79]
El daño de bola de fuego tambien esta bajo...
Testeado con Dr. Damage version 4.3.4

http://www.subeimagenes.com/img/bola-de-fuego-1306593.jpg

http://cata.openwow.com/spell=133

**Comment by Myst** [comment]
Reparado. Los cambios se aplican en el siguiente reinicio.
