### ISSUE TITLE
[Spell] Lista de hechizos y facultades bug de cada clase.

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#81]
Hola a todos! Me llamo Esteban, ingrese hace unos días al servidor mi cazador actual es Kaerie.
El objetivo de este post es crear solo un hilo con los bug recientes de cada clase ya sea habilidades, talentos y glifos e ir separando por clase, lo cual ustedes mencionen y los voy agregando, la condición es de la misma forma como pide http://foro.wowrage.com/index.php?/topic/61-reportando-errores-como-reportar/ para tener un orden lógico. No todos los hechizos tendrán fuente por que cambiaron mucho en wowhead y terminaria confundiendo.

Cazador:
Spell: Camuflaje “Te mezclas con el entorno y evitas que puedan seleccionarte como objetivo con ataques a distancia a ti y tu mascota, proporciona sigilo mientras no se muevan, se puede utilizar trampas pero cualquier daño que inflijas tu o tu mascota cancelara el efecto. No se puede usar en combate”
Fuente: http://es.wowhead.com/spell=51753/camuflaje y http://www.wowwiki.com/Camouflage
Error: Se rompe con cualquier habilidad no ofensiva como por ejemplo: bengala, marca del cazador, Aliviar mascota lo cual no debería y además distracción del pícaro nos lo rompe también.
Spell: Disuasión “Cuando se activa hace que desvíes todos los ataques cuerpo a cuerpo y a distancia, y los hechizos. Además reduce un 30% todo el daño recibido. No se puede atacar mientras esta activo. Dura 5seg”
Fuente: http://es.wowhead.com/spell=19263/disuasion
Error: Desvía algunos ataques pero entran algunos aturdir y habilidades como por ejemplo el pícaro puede usar puñalada y sus aturdir sin problema, si funcionara bien debería fallarlos aunque sea por la espalda.
Spell: Disparo de quimera “Disparo que inflige daño de Naturaleza con arma a distancia más 8567p de daño, reinicia la duración de tu Picadura de serpiente y te sana 5% de tu salud total”
Error: La formula esta mal calculada el daño es muy superior a lo debido, aquí la formula con un ejemplo:
                          Daño de arma+ ( RAP_0,732)+1620
RAP: Ataque de poder a distancia
Un ejemplo considerando el daño menor de mi arma y en el otro el mayor:
Min-Max           Daño arma      RAP_0,732       N°          Daño total
Daño menor     5161                 11393,58          1620      18.174,58
Daño mayor      6056                 11393,58          1620      19.069,58
Este daño es el que le efectuamos a un muñeco de entrenamiento o personaje sin temple, obviamente con temple y resistencias nos reducirá el daño. Por lo que he visto en muñeco da golpes de 22mil por lo que si esta alto.
Estos son por el momento seguiré agregando más hechizos, como de otras clases por lo que necesito que comenten los bug por favor, también avisare dentro del juego.

**Comment by Myst** [comment]
El reporte no cumple con los requisitos de los reportes, reporta un hechizo como máximo por cada reporte.
