### ISSUE TITLE
[Spell] Lista de hechizos y facultades bug de cada clase.

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#84]
Cazador:
Spell: Camuflaje “Te mezclas con el entorno y evitas que puedan seleccionarte como objetivo con ataques a distancia a ti y tu mascota, proporciona sigilo mientras no se muevan, se puede utilizar trampas pero cualquier daño que inflijas tu o tu mascota cancelara el efecto. No se puede usar en combate”
Fuente: http://es.wowhead.com/spell=51753/camuflaje y http://www.wowwiki.com/Camouflage
Error: Se rompe con cualquier habilidad no ofensiva como por ejemplo: bengala, marca del cazador, Aliviar mascota lo cual no debería y además distracción del pícaro nos lo rompe también.
Spell: Disuasión “Cuando se activa hace que desvíes todos los ataques cuerpo a cuerpo y a distancia, y los hechizos. Además reduce un 30% todo el daño recibido. No se puede atacar mientras esta activo. Dura 5seg”

**Comment by Myst** [comment]
Esto ya fue reparado.
