### ISSUE TITLE
[Spell] Lista de hechizos y facultades bug de cada clase

### ISSUE THREAD

**Issue by Roguexddd** [Myst/Bugtracker#85]
Fuente: http://es.wowhead.com/spell=19263/disuasion
Error: Desvía algunos ataques pero entran algunos aturdir y habilidades como por ejemplo el pícaro puede usar puñalada y sus aturdir sin problema, si funcionara bien debería fallarlos aunque sea por la espalda.
Spell: Disparo de quimera “Disparo que inflige daño de Naturaleza con arma a distancia más 8567p de daño, reinicia la duración de tu Picadura de serpiente y te sana 5% de tu salud total”
Error: La formula esta mal calculada el daño es muy superior a lo debido, aquí la formula con un ejemplo:
Daño de arma+ ( RAP0,732)+1620
RAP: Ataque de poder a distancia
Un ejemplo considerando el daño menor de mi arma y en el otro el mayor:
Min-Max Daño arma RAP0,732 N° Daño total
Daño menor 5161 11393,58 1620 18.174,58
Daño mayor 6056 11393,58 1620 19.069,58
Este daño es el que le efectuamos a un muñeco de entrenamiento o personaje sin temple, obviamente con temple y resistencias nos reducirá el daño. Por lo que he visto en muñeco da golpes de 22mil por lo que si esta alto.
Estos son por el momento seguiré agregando más hechizos, como de otras clases por lo que necesito que comenten los bug por favor, también avisare dentro del juego.

**Comment by Myst** [comment]
Reparado en el siguiente reinicio.
