### ISSUE TITLE
Bomba de humo [Rogue] [ID: 76577] Picaron inmortal 

### ISSUE THREAD

**Issue by dreyzar** [Myst/Bugtracker#86]
Explico detalladamente para esperar y tener la esperanza que algun dia lo fixearan...

Lo que hace esa skill es que crea una nube de humo donde el picaro no se puede elegir como objetivo ( hasta aca la skill esta funcionando perfecto).... OJO pero el picaro deberia recibir daño en area (Aoe), ¿porque deberia recibir daño si no se puede poner como objetivo?, bueno porque el daño en area no necesita colocar en objetivo para hacer daño.

Dicha skill deberia tener un rango de 8 metros... actualmente su rango es ilimitado (testeado con speed hack, creia que era 100 m lo que tenia pero nu )

en resumen esa habilidad hace al picaro inmortal por 5 segundos, ya sea para llevar bandera en bg y pasar en la cara de 10 players y que ni uno te toque... o tomar alguna base enfrente de todos y escaparte ileso... incluso matar a un player y que los demas solo te observen como lo haces.

Ojala lo fixees bro, habias dicho que para el 25 de diciembre  ibas a implementar el fix pero nunca llego xD

http://cata.openwow.com/spell=76577

**Comment by Zodiako** [comment]
Sobre todo el error más grosero de esta skill es que la bomba de humo parece que es hechada en todo Azeroth xD , debería un rango determinado, no ilimitado!

**Comment by Myst** [comment]
Reparado.
