### ISSUE TITLE
Disparo de Quimera

### ISSUE THREAD

**Issue by mjfinish** [Myst/Bugtracker#90]
Spell: Disparo de quimera http://es.wowhead.com/spell=53209/disparo-de-quimera “Disparo que inflige daño de Naturaleza con arma a distancia más 8567p de daño, reinicia la duración de tu Picadura de serpiente y te sana 5% de tu salud total”
Error: La formula esta mal calculada el daño es muy superior a lo debido, aquí la formula con un ejemplo:
Daño de arma+ ( RAP0,732)+1620
RAP: Ataque de poder a distancia
Un ejemplo considerando el daño menor de mi arma y en el otro el mayor:
Min-Max Daño arma RAP0,732 N° Daño total
Daño menor 5161 11393,58 1620 18.174,58
Daño mayor 6056 11393,58 1620 19.069,58
Este daño es el que le efectuamos a un muñeco de entrenamiento o personaje sin temple, obviamente con temple y resistencias nos reducirá el daño. Por lo que he visto en muñeco da golpes de 22mil por lo que si esta alto.

**Comment by Myst** [comment]
Reparado.
