### ISSUE TITLE
Reporte del Glifo del escudo atontador ( Paladín ) 

### ISSUE THREAD

**Issue by MjDaftpunk** [Myst/Bugtracker#91]
El Glifo http://es.wowhead.com/spell=56414/glifo-de-escudo-atontador solo se activa con el hechizo de escudo vengador ( teniendo escudo )  haciendo que este atonte a los objetivos.

ERROR :
el paladín represión puede usar ese glifo sin meter ningún poder de protección como lo requiere ni escudo, lo hace como un pasivo adicional.
![wowscrnshot_050815_194914](https://cloud.githubusercontent.com/assets/12310034/7548253/6f74f5f0-f5c7-11e4-8ecb-59b01c503c92.jpg)
![wowscrnshot_050815_194916](https://cloud.githubusercontent.com/assets/12310034/7548252/6f727686-f5c7-11e4-9690-b2177cec41aa.jpg)
![wowscrnshot_050815_194919](https://cloud.githubusercontent.com/assets/12310034/7548251/6f6fa708-f5c7-11e4-8b12-bd6a790d6b5f.jpg)
![wowscrnshot_050815_194926](https://cloud.githubusercontent.com/assets/12310034/7548254/6f792864-f5c7-11e4-825f-0edcdf79bebb.jpg)

Como se puede apreciar en las imágenes  al meter cualquier poder ( sentencia,  golpe del cruzado, veredicto del templario y exorcismo, este glifo se activa constantemente sin necesidad de escudo ni de un coldown

**Comment by Myst** [comment]
Reparado.
