### ISSUE TITLE
Reporte de [Infusión de Luz] (paladín)

### ISSUE THREAD

**Issue by MjDaftpunk** [Myst/Bugtracker#92]
El hechizo http://es.wowhead.com/spell=53576/infusion-de-luz cuando el choque sagrado saca critico reduce el tiempo de lanzamiento de cualquier hechizo sagrado en 1.5 ( luz sagrada o radiancia sagrada y destello de luz)

Error : 

EL hechizo Infusión de luz  luego de lanzar instantáneamente destello de luz en 1.50 seg http://es.wowhead.com/spell=19750/destello-de-luz  o lanzar cualquier hechizo de sanación ya sea Luz sagrada sigue activo por 14 segundos. teniendo la ventaja de que no se desvanezca al lanzar el hechizo, si no que permanezca activo 14 segundos de duración permitiendo castear instantáneamente  destello de luz en esos 14 segundos. POSTDATA: se puede castear de 7 a 10 destellos en esos 14 segundos.
![wowscrnshot_050915_002301](https://cloud.githubusercontent.com/assets/12310034/7548842/c160c9b0-f5e1-11e4-9dab-a6bd4e9fe0a6.jpg)
![wowscrnshot_050915_002302](https://cloud.githubusercontent.com/assets/12310034/7548843/c164d532-f5e1-11e4-8566-ad3967d4ca04.jpg)
![wowscrnshot_050915_002303](https://cloud.githubusercontent.com/assets/12310034/7548844/c167a87a-f5e1-11e4-96c7-f6f7adf0b3be.jpg)
![wowscrnshot_050915_002305](https://cloud.githubusercontent.com/assets/12310034/7548845/c16a1b32-f5e1-11e4-8a55-284546cce3f6.jpg)
![wowscrnshot_050915_002306](https://cloud.githubusercontent.com/assets/12310034/7548846/c1708238-f5e1-11e4-919e-9ed3679d1718.jpg)
![wowscrnshot_050915_002308](https://cloud.githubusercontent.com/assets/12310034/7548847/c181ef6e-f5e1-11e4-815f-56199ffbd236.jpg)
![wowscrnshot_050915_002310](https://cloud.githubusercontent.com/assets/12310034/7548848/c1858c96-f5e1-11e4-9924-64dfa54a0bc2.jpg)
![wowscrnshot_050915_002311](https://cloud.githubusercontent.com/assets/12310034/7548849/c1899ee4-f5e1-11e4-8ea6-93c709fa931b.jpg)
![wowscrnshot_050915_002312](https://cloud.githubusercontent.com/assets/12310034/7548850/c18cd528-f5e1-11e4-8f50-16d8259657e4.jpg)
![wowscrnshot_050915_002314](https://cloud.githubusercontent.com/assets/12310034/7548851/c190de5c-f5e1-11e4-8958-7ca2921ccf9f.jpg)

Como pueden ver en las imágenes y en el registro de combate del chat pueden ver las veces que he activado mi destello de luz instantaneamente  por un periodo de 14 segundos.

**Comment by Myst** [comment]
Reparado en el siguiente reinicio.
