### ISSUE TITLE
Reporte de Sanación Desinteresada ( Paladín )

### ISSUE THREAD

**Issue by MjDaftpunk** [Myst/Bugtracker#93]
Sanación desinteresada http://cata.openwow.com/spell=85804 si leemos el poder aparte de la reducción de palabra de gloria en 5 segundos, cuando sanas a un objetivo amistoso con la palabra de gloria aumenta el 50% la efectividad de las sanaciones realizadas y  aumenta el daño infligido por cada carga de poder sagrado ( 3 cargas 12% ) 

ERROR: 

Sanación desinteresada se activa sin curar a ningún objetivo y solo metiendo daño con sentencia, aumentado 4% el daño infligido a cualquier enemigo.

![wowscrnshot_050615_181407](https://cloud.githubusercontent.com/assets/12310034/7548932/b0114ad6-f5e6-11e4-8f44-9bd53713e384.jpg)
![wowscrnshot_050615_181518](https://cloud.githubusercontent.com/assets/12310034/7548933/b014af28-f5e6-11e4-9467-970ec14b841f.jpg)
![wowscrnshot_050615_181530](https://cloud.githubusercontent.com/assets/12310034/7548934/b0185592-f5e6-11e4-9855-7f33387e6633.jpg)
![wowscrnshot_050615_181548](https://cloud.githubusercontent.com/assets/12310034/7548936/b01e4af6-f5e6-11e4-9088-8b00d2b767a6.jpg)
![wowscrnshot_050615_181932](https://cloud.githubusercontent.com/assets/12310034/7548935/b01e4588-f5e6-11e4-96d7-f43d65c863ad.jpg)
![wowscrnshot_050615_181946](https://cloud.githubusercontent.com/assets/12310034/7548937/b023d3ae-f5e6-11e4-854e-e5ade380bd48.jpg)

**Comment by MjDaftpunk** [comment]
mete en 4% a 12 % dependiendo de cuanto poder sagrado tenga acumulado.

**Comment by MjDaftpunk** [comment]
se activa al meter sentencia o también palabra de gloria  como pueden observar en las imágenes.

**Comment by MjDaftpunk** [comment]
No necesariamente tienes que curar a un Objetivo amistoso, basta que te cures a ti mismo para que el beneficio de 4% - 8% o 12%  de daño adicional que te brinda dependiendo del poder sagrado que tengas se active.

**Comment by Myst** [comment]
Reparado.
