### ISSUE TITLE
Reporte del Glifo Sello de verdad (Paladín)

### ISSUE THREAD

**Issue by MjDaftpunk** [Myst/Bugtracker#95]
El glifo sello de verdad  hace que tu sello de verdad y sello de rectitud también otorguen pericia 10puntos http://cata.openwow.com/spell=59429 ( en wow head el glifo está actualizado y  solo pude contrastar con http://cata.openwow.com)

Error : 

Por más que te pongas el glifo la bonificación de pericia no la da para nada:

Sin glifo:  ( 19 de pericia )
![wowscrnshot_050915_044930](https://cloud.githubusercontent.com/assets/12310034/7549708/d6111ebc-f606-11e4-94dc-f6831b0f8842.jpg)

Con glifo :  ( 19 de pericia )

![wowscrnshot_050915_040013](https://cloud.githubusercontent.com/assets/12310034/7549710/f58a106e-f606-11e4-8928-9dfcc731b977.jpg)

Como pueden ver en las imágenes no da la bonificación de 10 de pericia

**Comment by Myst** [comment]
Para que funcione correctamente solo debes cerrar y volver a abrir los stats de tu pj. Acabo de comprobar de que funciona correctamente.
Mas información: http://eu.battle.net/wow/en/forum/topic/2601190478
