### ISSUE TITLE
Reporte del Hechizo Pilar de Escarcha (DK)

### ISSUE THREAD

**Issue by MjDaftpunk** [Myst/Bugtracker#99]
El pilar de escarcha es un Hechizo del  DK escarcha http://es.wowhead.com/spell=51271/pilar-de-escarcha ( no encontrado en cata.openwow ) que aumenta el poder de Escarcha y la fuerza del caballero de la Muerte un 15%. Otorga inmunidad a los efectos de movimiento externos, como los derribos. Dura 20 s.

ERROR:

Si tenes activo el hechizo no hace inmune cuando te derriba un warrior http://cata.openwow.com/spell=85388  
![wowscrnshot_051015_051133](https://cloud.githubusercontent.com/assets/12310034/7553876/67f5f74a-f6d3-11e4-9d55-58965d378325.jpg)

Como pueden ver tengo activado  el hechizo de Pilar de escarcha  y el warrior puede derribarme
Cuando el mismo poder dice " Otorga inmunidad a los efectos de movimiento externos, como los derribos"

**Comment by Myst** [comment]
esto ya fue reparado.
